# 🏡 NYC Airbnb Dataset: Data Cleaning, Standardization & Preparation for Power BI

## Introduction & Project Scope

This project focuses on the end-to-end data cleaning, validation, and standardization of the New York City Airbnb dataset to prepare it for high-integrity Business Intelligence (Power BI) reporting. Real-world marketplace data often suffers from inconsistencies, missing spatial metadata, typographical errors, and unverified records. Rather than applying naive row deletions or synthetic imputations—which introduce analytical bias—this pipeline enforces a strict, data-integrity-first approach. By combining domain-specific logic, hierarchical string standardization, spatial proximity analysis (k-NN), and file format optimizations (Parquet), this preparation layer guarantees that downstream analytical models and KPIs reflect factual operational realities.

## <span style=" color:red"> Import Libraries, Loading the Dataset and Initial Exploration

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import missingno as msno
import plotly.express as px
import folium
from folium import plugins

pd.set_option("display.max_columns", None) 
pd.set_option('display.max_rows', None)

import warnings
warnings.filterwarnings("ignore")

In [2]:
df0 = pd.read_csv("Airbnb_Open_Data.csv")
df = df0.copy()

In [3]:
df.head(2)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN

In [4]:
df.info()

# The dataset consists of 102,599 rows and 26 columns with data types distributed as float64 (9), int64 (2), and object (15). 
# Initial checks indicate that all columns contain null values, with the exception of id, host_id, and room_type. 
# Notably, the license column is almost entirely missing, with non-null values present in only 2 records.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [5]:
df.shape

(102599, 26)

In [6]:
df.columns # Let's inspect the column names.

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [7]:
# and standardize the column names.

column_names = {
    'NAME': 'name',
    'host id': 'host_id',
    'host_identity_verified': 'host_identity_verified',
    'host name': 'host_name',
    'neighbourhood group': 'neighbourhood_group',
    'room type': 'room_type',
    'Construction year': 'construction_year',
    'service fee': 'service_fee',
    'minimum nights': 'minimum_nights',
    'number of reviews': 'number_of_reviews',
    'last review': 'last_review',
    'reviews per month': 'reviews_per_month',
    'review rate number': 'review_rate_number',
    'calculated host listings count': 'calculated_host_listings_count',
    'availability 365': 'availability_365',
    'country code': 'country_code',
    'instant_bookable': 'instant_bookable',
    'cancellation_policy': 'cancellation_policy',
    'house_rules': 'house_rules'
}

df.rename(columns=column_names, inplace=True)

In [8]:
df.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license'],
      dtype='object')

In [9]:
df.dtypes #Checking Data Types

id                                  int64
name                               object
host_id                             int64
host_identity_verified             object
host_name                          object
neighbourhood_group                object
neighbourhood                      object
lat                               float64
long                              float64
country                            object
country_code                       object
instant_bookable                   object
cancellation_policy                object
room_type                          object
construction_year                 float64
price                              object
service_fee                        object
minimum_nights                    float64
number_of_reviews                 float64
last_review                        object
reviews_per_month                 float64
review_rate_number                float64
calculated_host_listings_count    float64
availability_365                  float64
house_rules                        object
license                            object
dtype: object

In [10]:
df["construction_year"] = df["construction_year"].astype("Int64")

# Converted float/numeric columns with missing values to Pandas' nullable integer format (Int64). 
# Standard int64 fails when NaN values are present, 
# whereas Int64 supports missing data while maintaining integer integrity for Power BI export.

In [11]:
# Stripped currency symbols ($), commas, and whitespace from price and service_fee string columns, 
# then converted them to numeric values using pd.to_numeric() with errors='coerce' to handle unparseable entries safely.

df["price"] = (
    df["price"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)
df["price"] = pd.to_numeric(df["price"], errors="coerce")

df["service_fee"] = (
    df["service_fee"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)
df["service_fee"] = pd.to_numeric(df["service_fee"], errors="coerce")

In [12]:
df["minimum_nights"].dropna().loc[
    df["minimum_nights"].dropna() % 1 != 0
]

# Verified that the floating-point minimum_nights values contain no fractional components other than .0. 
# This ensures that converting minimum_nights from float64 to Int64 proceeds without any data loss.

Series([], Name: minimum_nights, dtype: float64)

In [13]:
df["minimum_nights"] = df["minimum_nights"].astype("Int64")

In [14]:
# Replicated Precision Check;

df["number_of_reviews"].dropna().loc[
    df["number_of_reviews"].dropna() % 1 != 0
]

Series([], Name: number_of_reviews, dtype: float64)

In [15]:
df["number_of_reviews"] = df["number_of_reviews"].astype("Int64")

In [16]:
df["last_review"] = pd.to_datetime(df["last_review"])

# DateTime Conversion: Converted the column to datetime64 format to enable time-series analysis and proper date filtering in Power BI.

In [17]:
# Replicated Precision Check;

df["review_rate_number"].dropna().loc[
    df["review_rate_number"].dropna() % 1 != 0
]

Series([], Name: review_rate_number, dtype: float64)

In [18]:
df["review_rate_number"] = df["review_rate_number"].astype("Int64")

In [19]:
# Replicated Precision Check;

df["calculated_host_listings_count"].dropna().loc[
    df["calculated_host_listings_count"].dropna() % 1 != 0
]

Series([], Name: calculated_host_listings_count, dtype: float64)

In [20]:
df["calculated_host_listings_count"] = df["calculated_host_listings_count"].astype("Int64")

In [21]:
# Replicated Precision Check;

df["availability_365"].dropna().loc[
    df["availability_365"].dropna() % 1 != 0
]

Series([], Name: availability_365, dtype: float64)

In [22]:
df["availability_365"] = df["availability_365"].astype("Int64")

In [23]:
df["instant_bookable"] = (
    df["instant_bookable"]
    .astype(str)
    .str.strip()
    .str.upper()
    .map({"TRUE": True, "FALSE": False})
)

df["instant_bookable"] = df["instant_bookable"].astype("boolean")

# Boolean Standardization & Null Preservation: 
# Standardized text strings to uppercase (TRUE/FALSE) and mapped them to boolean values. 
# Using Pandas' nullable boolean dtype ensures that original missing (NaN) values remain intact without forcing them to False.

In [24]:
df.dtypes

id                                         int64
name                                      object
host_id                                    int64
host_identity_verified                    object
host_name                                 object
neighbourhood_group                       object
neighbourhood                             object
lat                                      float64
long                                     float64
country                                   object
country_code                              object
instant_bookable                         boolean
cancellation_policy                       object
room_type                                 object
construction_year                          Int64
price                                    float64
service_fee                              float64
minimum_nights                             Int64
number_of_reviews                          Int64
last_review                       datetime64[ns]
reviews_per_month                        float64
review_rate_number                         Int64
calculated_host_listings_count             Int64
availability_365                           Int64
house_rules                               object
license                                   object
dtype: object

In [25]:
df.head(1)

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020,966.0,193.0,10,9,2021-10-19,0.21,4,6,286,Clean up and treat the home the way you'd like...,NaN

## <span style=" color:red"> General Inspection of Numeric Features

In [26]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
id,102599.0,29146234.52213,1001254.0,15085814.5,29136603.0,43201198.0,57367417.0,16257505.607309
host_id,102599.0,49254111474.328667,123600518.0,24583328475.0,49117739352.0,73996495817.0,98763129024.0,28538996644.374817
lat,102591.0,40.728094,40.49979,40.68874,40.72229,40.76276,40.91697,0.055857
long,102591.0,-73.949644,-74.24984,-73.98258,-73.95444,-73.93235,-73.70522,0.049521
construction_year,102385.0,2012.487464,2003.0,2007.0,2012.0,2017.0,2022.0,5.765556
price,102352.0,625.293536,50.0,340.0,624.0,913.0,1200.0,331.671614
service_fee,102326.0,125.026924,10.0,68.0,125.0,183.0,240.0,66.325739
minimum_nights,102190.0,8.135845,-1223.0,2.0,3.0,5.0,5645.0,30.553781
number_of_reviews,102416.0,27.483743,0.0,1.0,7.0,30.0,1024.0,49.508954
last_review,86706,2019-06-12 03:40:52.065601024,2012-07-11 00:00:00,2018-10-28 00:00:00,2019-06-14 00:00:00,2019-07-05 00:00:00,2058-06-16 00:00:00,NaN
reviews_per_month,86720.0,1.374022,0.01,0.22,0.74,2.0,90.0,1.746621
review_rate_number,102273.0,3.279106,1.0,2.0,3.0,4.0,5.0,1.284657
calculated_host_listings_count,102280.0,7.936605,1.0,1.0,1.0,2.0,332.0,32.21878
availability_365,102151.0,141.133254,-10.0,3.0,96.0,269.0,3677.0,135.435024

**Upon inspection**, we observe **extreme anomalies in availability_365 and minimum_nights**, specifically **negative values** and **unrealistic high numbers:**

**1. Outlier Handling for minimum_nights**: Upon inspection, we identified negative values and unrealistic high numbers in the minimum_nights feature. Logically, a minimum stay cannot be less than 1 night, and per New York City short-term rental regulations, it cannot exceed 365 nights.

In [27]:
# Checking the number of records where minimum_nights exceeds 365 nights;

over_365_count = (df["minimum_nights"] > 365).sum()
print(f"Number of rows where minimum_nights exceeds 365 nights: {over_365_count}")

# Displaying these outlier records;

df[df["minimum_nights"] > 365][["id", "name", "minimum_nights"]]

Number of rows where minimum_nights exceeds 365 nights: 35

,id,name,minimum_nights
167,1093570,Convenient cozy cheap apt Manhattan,371
186,1104064,SAFE AND BEAUTIFUL ACCOMODATION,366
263,1146591,"Private, Large & Sunny Top Floor Apt w/W&D",399
299,1166474,Bright Beautiful Brooklyn,452
350,1194641,LARGE 1BR (CONV 2BR) CROWN HEIGHTS,3455
473,1262574,Spacious Quiet rm - 20mins to Midtown,398
1306,1722640,800sqft apartment with huge terrace,370
2855,2578153,NaN,1000
5768,4187002,Prime W. Village location 1 bdrm,1250
7356,5064055,Beautiful Fully Furnished 1 bed/bth,500
8015,5428021,Wonderful Large 1 bedroom,500
10830,6982745,Brand New Luxury Apt Lease Takeover,480
11194,7183782,Zen Room in Crown Heights Brooklyn,500
13405,8404918,Historic Designer 2 Bed. Apartment,999
14286,8891494,Peaceful apartment close to F/G,500
15947,9808864,"Bright Luxury Studio, Central Loc.",366
26342,15550023,Beautiful place in Brooklyn! #2,999
34488,20049058,Not available,400
38665,22356016,Shared Studio (females only),999
42354,24393450,Park views and city fun for July & August,452
42369,24401735,Private room in a perfect location in the city,954
42398,24417751,Bedroom in Prime Bushwick,5645
42407,24422722,Modern & Cozy 2 BR Private Apartment in Brooklyn,2645
47621,27302414,Williamsburg Apartment,500
67608,38341234,Conveniently Located Cozy and Quiet UES Apartment,500
69482,39376245,800sqft apartment with huge terrace,370
71031,40231757,NaN,1000
72663,41133111,Brand New Luxury Apt Lease Takeover,480
73027,41334148,Zen Room in Crown Heights Brooklyn,500
83506,47121700,Beautiful place in Brooklyn! #2,999
84108,47454184,Peaceful apartment close to F/G,500
85769,48371555,"Bright Luxury Studio, Central Loc.",366
91347,51452284,Clean 1br w/Parking Incl. also 10min near JFK...,458
97421,54806954,Not available,400
99691,56060675,Cozy Home in Harlem ✨,825

In [28]:
# Count and proportion of rows where minimum_nights > 365;

over_365_count = (df["minimum_nights"] > 365).sum()
over_365_ratio = (over_365_count / len(df)) * 100

print(f"365 geceden fazla olan satır sayısı: {over_365_count}")
print(f"Toplam veriye oranı: %{over_365_ratio:.4f}")

365 geceden fazla olan satır sayısı: 35
Toplam veriye oranı: %0.0341

In [29]:
# Displaying rows with negative minimum_nights values; 

df[df["minimum_nights"] < 0][
    ["id", "name", "neighbourhood", "room_type", "minimum_nights"]
]

,id,name,neighbourhood,room_type,minimum_nights
176,1098541,BROOKLYN VICTORIAN STYLE SUITE.....,Fort Greene,Private room,-10
352,1195746,"Beautiful, Bright’s, Warm & Spacious 1.5BR Apt",Crown Heights,Entire home/apt,-5
398,1221151,SUPER BIG AND COZY PRIVATE BEDROOM,Kensington,Private room,-1
421,1233854,Charming Nolita Apartment!!,Nolita,Entire home/apt,-10
441,1244900,Cozy apartment in a brownstone,Harlem,Entire home/apt,-12
478,1265335,Charming upper west side apartment,Upper West Side,Entire home/apt,-2
525,1291294,Chateau Style Brooklyn Loft for Singles or Cou...,Bedford-Stuyvesant,Entire home/apt,-3
42446,24444262,"Cozy room in bright, spacious apartment",Hunts Point,Private room,-1223
42500,24474086,2bd BOUTIQUE Apartament in the heart of MANHA...,Hell's Kitchen,Entire home/apt,-365
42538,24495073,Newly Renovated Garden Apartment,Bedford-Stuyvesant,Entire home/apt,-200
69749,39523709,Amazing location! 10ft from L train,Williamsburg,Private room,-125
91271,51410309,Beautiful modern & large 2 bedroom,Midtown,Entire home/apt,-10
91357,51457807,Cozy Brooklyn Apartment,Gowanus,Shared room,-10

In [30]:
df[df["minimum_nights"] < 0]

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules,license
176,1098541,BROOKLYN VICTORIAN STYLE SUITE.....,83631499592,unconfirmed,Frederick,Brooklyn,Fort Greene,40.69098,-73.97113,United States,US,False,flexible,Private room,2008,1155.0,231.0,-10,213,2019-06-24,2.00,5,2,19,There is no smoking on the property. No outsid...,NaN
352,1195746,"Beautiful, Bright’s, Warm & Spacious 1.5BR Apt",2227683633,unconfirmed,Grant,Brooklyn,Crown Heights,40.67174,-73.95663,NaN,NaN,<NA>,NaN,Entire home/apt,2009,73.0,15.0,-5,104,2019-06-21,1.04,5,1,31,We are a second-floor apartment so please do n...,NaN
398,1221151,SUPER BIG AND COZY PRIVATE BEDROOM,50336791874,verified,Tucker,Brooklyn,Kensington,40.64302,-73.97255,United States,US,False,flexible,Private room,2015,779.0,156.0,-1,82,2019-05-19,0.94,2,2,131,"no inside smoking, quiet(ish) after 11, help y...",NaN
421,1233854,Charming Nolita Apartment!!,7389895192,verified,Belinda,Manhattan,Nolita,40.72094,-73.99706,United States,US,False,flexible,Entire home/apt,2008,874.0,175.0,-10,68,2019-06-10,0.69,5,1,13,NaN,NaN
441,1244900,Cozy apartment in a brownstone,81186886194,verified,Adelaide,Manhattan,Harlem,40.80497,-73.95016,United States,US,False,moderate,Entire home/apt,2021,920.0,184.0,-12,203,2019-07-06,2.14,5,3,77,NaN,NaN
478,1265335,Charming upper west side apartment,89878315253,unconfirmed,Alen,Manhattan,Upper West Side,40.77886,-73.98042,United States,US,True,strict,Entire home/apt,2022,410.0,82.0,-2,129,2019-06-07,1.33,2,1,381,Please remember that this is a residential bui...,NaN
525,1291294,Chateau Style Brooklyn Loft for Singles or Cou...,2631536622,verified,Carlos,Brooklyn,Bedford-Stuyvesant,40.68967,-73.95445,United States,US,False,moderate,Entire home/apt,2022,413.0,83.0,-3,42,2019-05-18,0.44,5,1,292,BUILDING IS RESIDENTIAL. DOCTORS AND NURSES WH...,NaN
42446,24444262,"Cozy room in bright, spacious apartment",84040511136,verified,Steven,Bronx,Hunts Point,40.81731,-73.89052,United States,US,False,moderate,Private room,2003,1200.0,240.0,-1223,0,NaT,NaN,2,4,341,Smoking is strictly prohibited. Your pets are ...,NaN
42500,24474086,2bd BOUTIQUE Apartament in the heart of MANHA...,2679070022,unconfirmed,Tom,Manhattan,Hell's Kitchen,40.76694,-73.98773,United States,US,True,flexible,Entire home/apt,2009,711.0,142.0,-365,13,2019-07-07,5.91,4,4,0,Please pick up/drop packet with front desk con...,NaN
42538,24495073,Newly Renovated Garden Apartment,98469733112,verified,Margie,Brooklyn,Bedford-Stuyvesant,40.68470,-73.94350,United States,US,True,moderate,Entire home/apt,2022,85.0,17.0,-200,3,2019-04-23,1.06,2,1,157,No smoking or pets allowed and we request that...,NaN
69749,39523709,Amazing location! 10ft from L train,62132542936,verified,Giorgia & Benjamin,Brooklyn,Williamsburg,40.71534,-73.94906,United States,US,False,moderate,Private room,2012,328.0,66.0,-125,146,2019-06-23,1.78,1,1,46,NaN,NaN
91271,51410309,Beautiful modern & large 2 bedroom,13861414317,unconfirmed,Vikas,Manhattan,Midtown,40.74433,-73.98318,United States,US,False,moderate,Entire home/apt,2007,772.0,154.0,-10,0,NaT,NaN,3,1,0,Please remember that this is a residential bui...,NaN
91357,51457807,Cozy Brooklyn Apartment,63988893317,verified,Daniella,Brooklyn,Gowanus,40.67070,-73.99118,United States,US,True,moderate,Shared room,2014,1177.0,235.0,-10,9,2017-05-08,0.31,2,1,0,"No smoking, No pets. No shoes in the house. Vi...",NaN

In [31]:
# Rows where minimum_nights is less than 1 or greater than 365;

outlier_mask = (df["minimum_nights"] < 1) | (df["minimum_nights"] > 365)

# Count and Rate;

outlier_count = outlier_mask.sum()
outlier_ratio = (outlier_count / len(df)) * 100

print(f"Total number of rows less than 1 or greater than 365: {outlier_count}")
print(f"Percentage of total data: {outlier_ratio:.4f}%")

Total number of rows less than 1 or greater than 365: 48
Percentage of total data: 0.0468%

In [32]:
df = df[(df["minimum_nights"] >= 1) & (df["minimum_nights"] <= 365)].copy()

Diagnostic checks revealed 48 rows where minimum_nights fell outside the valid range of [1, 365]. 
Because these anomalous entries represent an extremely negligible portion of the dataset (0.0468%), removing them outright cleanses the feature without introducing bias or reducing the statistical power of subsequent analysis.

In [33]:
print(f"Updated Total Row Count: {len(df)}")
print(f"minimum_nights range: {df['minimum_nights'].min()} - {df['minimum_nights'].max()}")

Updated Total Row Count: 102142
minimum_nights range: 1 - 365

In [34]:
# Count and ratio of availability_365 values exceeding 365 days;

avail_over_365_count = (df["availability_365"] > 365).sum()
avail_over_365_ratio = (avail_over_365_count / len(df)) * 100

print(f"Number of rows with availability > 365: {avail_over_365_count}")
print(f"Percentage of total data: {avail_over_365_ratio:.4f}%")

Number of rows with availability > 365: 2765
Percentage of total data: 2.7070%

In [35]:
# Count of negative values in availability_365;

avail_neg_count = (df["availability_365"] < 0).sum()
print(f"Number of negative availability values: {avail_neg_count}")

Number of negative availability values: 426

Combined, these anomalous entries account for 3.1240% of the dataset. Since dropping these rows would needlessly discard valid information across other attributes (e.g., location, price, room type), converting only these specific cells to NaN eliminates measurement error while preserving overall dataset completeness for Power BI modeling.

In [36]:
# availability_365: Flagging negative (<0) and values exceeding 365 as cell-level NaN;

df.loc[(df["availability_365"] < 0) | (df["availability_365"] > 365), "availability_365"] = np.nan

# Final verification;

print(f"Remaining Total Row Count: {len(df)}")
print("availability_365 'NaN' count:", df["availability_365"].isna().sum())
print("availability_365 min - max:", df["availability_365"].min(), "-", df["availability_365"].max())

Remaining Total Row Count: 102142
availability_365 'NaN' count: 3615
availability_365 min - max: 0 - 365

**Outlier Analysis & Cleaning Strategy Conclusion**

During the outlier analysis, physically impossible values (negative numbers and values exceeding the 365-day annual limit) were identified in the minimum_nights and availability_365 features. The following actions were executed:

**minimum_nights Feature:** A total of 48 rows (0.0468% of the dataset) contained logically invalid values (less than 1 night or greater than 365 nights). Since the impact of this removal on sample representativeness is negligible, these 48 rows were filtered out entirely.

**availability_365 Feature:** A total of 3,191 invalid observations (3.1240% of the dataset) were identified, consisting of negative values (426 rows) and records exceeding 365 days (2,765 rows). Dropping 3% of the dataset would result in significant information loss, stripping away valid, highly valuable attributes such as price, location, and room type. To prevent unnecessary data loss, a cell-level cleaning approach was adopted, converting these specific invalid entries to missing values (NaN).

**Outcome:** This dual-strategy ensures that calculated metrics in Power BI (e.g., average length of stay, annual availability rates) remain uncorrupted while fully preserving the dimensional integrity of listings for downstream analysis.

In [37]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
id,102142.0,29190159.041824,1001254.0,15138697.0,29192661.0,43239445.0,57367417.0,16248338.036273
host_id,102142.0,49258329726.053757,123600518.0,24583294859.0,49121436885.0,74006192315.0,98763129024.0,28537968280.756256
lat,102134.0,40.728089,40.49979,40.688733,40.72229,40.76277,40.91697,0.055866
long,102134.0,-73.949623,-74.24984,-73.98256,-73.95444,-73.93233,-73.70522,0.049526
construction_year,101940.0,2012.486747,2003.0,2007.0,2012.0,2017.0,2022.0,5.764688
price,101895.0,625.322302,50.0,340.0,625.0,913.0,1200.0,331.664484
service_fee,101869.0,125.032463,10.0,68.0,125.0,183.0,240.0,66.324395
minimum_nights,102142.0,7.856513,1.0,2.0,3.0,5.0,365.0,17.05118
number_of_reviews,101961.0,27.43649,0.0,1.0,7.0,30.0,1024.0,49.393521
last_review,86330,2019-06-12 01:39:24.832619008,2012-07-11 00:00:00,2018-10-28 00:00:00,2019-06-14 00:00:00,2019-07-05 00:00:00,2058-06-16 00:00:00,NaN
reviews_per_month,86338.0,1.373167,0.01,0.22,0.74,2.0,90.0,1.745033
review_rate_number,101837.0,3.279869,1.0,2.0,3.0,4.0,5.0,1.284527
calculated_host_listings_count,101823.0,7.934524,1.0,1.0,1.0,2.0,332.0,32.194386
availability_365,98527.0,134.460737,0.0,2.0,90.0,254.0,365.0,129.802427

## <span style=" color:red"> Missing Value Inspection and Handling

In [38]:
df.isnull().sum().sort_values(ascending=False) # Checking Missing Values.

license                           102140
house_rules                        51920
last_review                        15812
reviews_per_month                  15804
availability_365                    3615
country                              531
host_name                            404
calculated_host_listings_count       319
review_rate_number                   305
host_identity_verified               278
service_fee                          273
price                                247
name                                 242
construction_year                    202
number_of_reviews                    181
country_code                         122
instant_bookable                      96
cancellation_policy                   75
neighbourhood_group                   28
neighbourhood                         15
lat                                    8
long                                   8
host_id                                0
id                                     0
minimum_nights                         0
room_type                              0
dtype: int64

In [39]:
df.isnull().sum().sum() # Total missing value.

np.int64(192625)

In [40]:
(df.isnull().mean() * 100).sort_values(ascending=False).round(2) # Missing Value Rates.

license                           100.00
house_rules                        50.83
last_review                        15.48
reviews_per_month                  15.47
availability_365                    3.54
country                             0.52
host_name                           0.40
calculated_host_listings_count      0.31
review_rate_number                  0.30
host_identity_verified              0.27
service_fee                         0.27
price                               0.24
name                                0.24
construction_year                   0.20
number_of_reviews                   0.18
country_code                        0.12
instant_bookable                    0.09
cancellation_policy                 0.07
neighbourhood_group                 0.03
neighbourhood                       0.01
lat                                 0.01
long                                0.01
host_id                             0.00
id                                  0.00
minimum_nights                      0.00
room_type                           0.00
dtype: float64

In [41]:
df[df["license"].notna()]

# The 'license' column is missing in all but two rows.
# Since there is insufficient data to impute missing values or perform meaningful analysis, we drop this column.

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules,license
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,verified,Christina,Brooklyn,Williamsburg,40.71764,-73.95689,United States,US,True,strict,Private room,2010,702.0,140.0,1,1,2016-01-03,0.02,1,1,191,"Dear Guest, Thank you for appreciating that I ...",41662/AL
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,unconfirmed,Christina,Brooklyn,Williamsburg,40.71764,-73.95689,United States,US,True,flexible,Private room,2010,702.0,140.0,1,1,2016-01-03,0.02,1,1,0,NaN,41662/AL

In [42]:
df.drop(columns=["license"], inplace=True)

In [43]:
df["house_rules"].head(5)

# Because these values cannot be reliably or accurately imputed without introducing synthetic bias, 
# they have been intentionally left as NaN.

0    Clean up and treat the home the way you'd like...
1    Pet friendly but please confirm with me if the...
2    I encourage you to use my kitchen, cooking and...
3                                                  NaN
4    Please no smoking in the house, porch or on th...
Name: house_rules, dtype: object

In [44]:
df["country"].unique() 

# Since our dataset is centered on New York Airbnb listings and all existing unique non-null values are 'United States',
# we decided to impute the null values with 'United States'.

array(['United States', nan], dtype=object)

In [45]:
df["country"] = df["country"].fillna("United States")

In [46]:
df["country_code"].unique()

# Similarly, all null values will be imputed with 'US'.

array(['US', nan], dtype=object)

In [47]:
df["country_code"] = df["country_code"].fillna("US")

In [48]:
df[["last_review","reviews_per_month","review_rate_number","number_of_reviews"]].head(10)

# These columns have missing values across all four fields, or at least the first three. 
# Verification shows that the remaining columns in these rows contain complete data, 
# indicating that these listings simply received no reviews. 
# Therefore, we retain these rows as they provide valuable data for other analytical dimensions.

# Additionally, some rows have NaN for 'last_review' and 'reviews_per_month', and 0 for 'number_of_reviews', 
# yet contain a valid 'review_rate_number'. 
# Lacking internal documentation on the rating system architecture, we cannot draw definitive conclusions. 
# However, this discrepancy likely stems from a different evaluation workflow—for instance, 
# listings that received a star rating without a written review.

  last_review  reviews_per_month  review_rate_number  number_of_reviews
0  2021-10-19               0.21                   4                  9
1  2022-05-21               0.38                   4                 45
2         NaT                NaN                   5                  0
3  2019-07-05               4.64                   4                270
4  2018-11-19               0.10                   3                  9
5  2019-06-22               0.59                   3                 74
6  2017-10-05               0.40                   5                 49
7  2017-10-05               0.40                   5                 49
8  2019-06-24               3.47                   3                430
9  2017-07-21               0.99                   5                118

In [49]:
df[
    df["last_review"].isna() &
    df["reviews_per_month"].isna() &
    df["review_rate_number"].isna() &
    (df["number_of_reviews"] == 0)
]

# When checking rows where 'last_review', 'reviews_per_month', and 'review_rate_number' are null while 'number_of_reviews' is 0,
# we observe that all other columns contain complete data.
# Therefore, we can infer that these listings simply have not received any reviews or ratings yet.
# To avoid data loss, we retain these rows as they provide valuable insights across other features.

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules
27,1016248,Magnifique Suite au N de Manhattan - vue Cloitres,38811420224,verified,Adrianna,Manhattan,Inwood,40.86754,-73.92639,United States,US,<NA>,strict,Private room,2017,274.0,55.0,4,0,NaT,NaN,<NA>,1,96,To treat our home with respect. No smoking in...
37,1021771,Clean and Quiet in Brooklyn,26207748876,verified,Arthur,Brooklyn,Bedford-Stuyvesant,40.68876,-73.94312,United States,US,False,moderate,Private room,2004,203.0,41.0,60,0,NaT,NaN,<NA>,1,294,NO Shoes in the house. This is why my house is...
266,1148248,"HOSTING YOUR SUNNY, SPACIOUS NYC ROOM",84001079377,verified,NaN,Manhattan,Inwood,40.86648,-73.92630,United States,US,False,strict,Private room,2003,373.0,75.0,7,0,NaT,NaN,<NA>,2,<NA>,NaN
268,1149352,Prime East Village 1 Bedroom,28535518402,unconfirmed,NaN,Manhattan,East Village,40.72807,-73.98594,United States,US,True,flexible,Entire home/apt,2012,136.0,27.0,3,0,NaT,NaN,<NA>,1,<NA>,1) We live in a quiet neighborhood so no loud ...
487,1270306,Very close to Downtown Awesome Private Apartment,7445813909,unconfirmed,Antony,Brooklyn,Gravesend,40.60452,-73.97103,United States,US,True,flexible,Entire home/apt,2021,762.0,152.0,7,0,NaT,NaN,<NA>,2,159,NaN
659,1365302,1 Bedroom Available In My Two Bedroom Flat,37408540678,verified,Scott,Brooklyn,Crown Heights,40.67495,-73.95563,United States,US,False,flexible,Private room,2009,69.0,14.0,3,0,NaT,NaN,<NA>,1,158,All Renters and Guests must be 25 years of age...
792,1438758,One bedroom sharing Bathroom,26184450237,unconfirmed,Harris,Brooklyn,Cypress Hills,40.67889,-73.86404,United States,US,False,flexible,Private room,2012,904.0,181.0,7,0,NaT,NaN,<NA>,1,255,NaN
794,1439862,Huge Williamsburg Loft..Perfect for Big Groups!,74128844694,verified,Tucker,Brooklyn,Williamsburg,40.70766,-73.95191,United States,US,True,flexible,Entire home/apt,2005,777.0,155.0,7,0,NaT,NaN,<NA>,2,109,It is VERY important to me that you respect my...
860,1476314,Fully Furnished 1B/1BTH UWS GEM 1 YR Sublease,44588815342,verified,Stewart,Manhattan,Upper West Side,40.78012,-73.98439,United States,US,True,moderate,Entire home/apt,2007,316.0,63.0,1,0,NaT,NaN,<NA>,1,302,"Unlike most other Airbnb listings, what we do ..."
12148,7710676,Stunning 2 bd home in historic limestone,38570550324,unconfirmed,Crystal,Brooklyn,Bedford-Stuyvesant,40.69156,-73.94276,United States,US,False,flexible,Entire home/apt,2007,453.0,91.0,7,0,NaT,NaN,<NA>,1,277,We expect travelers to leave the apartment in ...
12149,7711229,Modern Williamsburg Apartment,92269054044,unconfirmed,Andrew,Brooklyn,Williamsburg,40.71970,-73.95519,United States,US,True,strict,Entire home/apt,2009,1023.0,205.0,4,0,NaT,NaN,<NA>,1,47,No Smoking No Pets
36247,21020554,Bronx Apartment,93545392878,unconfirmed,Rosalyn,Bronx,Edenwald,40.88805,-73.83248,United States,US,True,strict,Entire home/apt,2019,207.0,41.0,15,0,NaT,NaN,<NA>,1,89,"No smoking, no pets. Rest of the house is a mi..."
36260,21027734,Times Square Prime Two Bedroom Near Port Autho...,73112075557,unconfirmed,Ryan,Manhattan,Hell's Kitchen,40.75768,-73.99417,United States,US,False,strict,Entire home/apt,2020,1169.0,234.0,30,0,NaT,NaN,<NA>,1,333,Must be 21 to book No loud music No parties No...
38833,22448802,Cozy Two Bedroom Apartment in Greenpoint,53159546615,unconfirmed,Andre,Brooklyn,Greenpoint,40.72944,-73.95395,United States,US,True,strict,Entire home/apt,2006,406.0,81.0,2,0,NaT,NaN,<NA>,1,0,Please do not smoke in the house. Please no p...
42613,24536496,habitacion con entrada privada a 20 min de manhat,26322674219,verified,Carolina,Brooklyn,Bushwick,40.70083,-73.91220,United States,US,False,strict,Private room,2007,292.0,58.0,2,0,NaT,NaN,<NA>,2,125,"- No smoking inside the house, we have a porch..."
46873,26889294,Astoria 2nd Floor,98374832362,unconfirmed,Sam,Queens,Long Island City,40.76117,-73.93038,United States,US,False,strict,Entire home/apt,2019,110.0,22.0,4,0,NaT,NaN,<NA>,1,39,- No shoes in apartment - No parties - Enjoy y...
46874,26889846,Gorgeous Luxury Studio!!,17718122061,unconfirmed,Dave,Manhattan,Hell's Kitchen,40.77044,-73.99126,United States,US,True,moderate,Entire home/apt,2005,927.0,185.0,3,0,NaT,NaN,<NA>,1,29,NaN
46875,26890399,Beautiful studio basement in Bushwick,35267668421,verified,Giuliana,Brooklyn,Bushwick,40.70364,-73.92679,United States,US,False,moderate,Private room,2017,1158.0,232.0,2,0,NaT,NaN,<NA>,1,57,"No smoking, no pets."
46879,26892608,Harmonious Bright Bedroom,20076203144,verified,Valentina,Brooklyn,Bushwick,40.70385,-73.91694,United States,US,False,flexible,Private room,2017,178.0,36.0,2,0,NaT,NaN,<NA>,3,314,"No smoking, No animals—we already have enough!..."
46880,26893160,Forest Hills Charming 1 bdrm apartment!,6426106681,verified,Sasha,Queens,Forest Hills,40.72085,-73.84088,United States,US,True,strict,Entire home/apt,2012,120.0,24.0,1,0,NaT,NaN,<NA>,1,7,"We expect guests to be clean, neat and respect..."
46881,26893712,4BR/3BA Triplex w/ Patio (Empire State Building!),4835077219,verified,Emilia & Jonathan,Manhattan,Kips Bay,40.74337,-73.97726,United States,US,False,strict,Entire home/apt,2020,320.0,64.0,3,0,NaT,NaN,<NA>,1,19,Greetings! Check-in: 5pm onwards - please cont...
46893,26900340,NIGHT CRAS PAD,85605428093,unconfirmed,Nancy,Queens,Jackson Heights,40.74908,-73.87961,United States,US,True,moderate,Shared room,2012,967.0,193.0,1,0,NaT,NaN,<NA>,<NA>,341,This is a non smoking house. Quiet hours are ...
46896,26901997,Duplex Residence with Breathtaking NYC View!,41295784874,verified,NuAve,Manhattan,Flatiron District,40.73942,-73.98648,United States,US,False,flexible,Entire home/apt,2010,912.0,182.0,7,0,NaT,NaN,<NA>,<NA>,178,We take great care of our home and want our gu...
46897,26902549,Prospect Park Hostel- Male Long Term Stay-1,9262572770,unconfirmed,Elizabeth,Brooklyn,Flatbush,40.64946,-73.96041,United States,US,False,flexible,Shared room,2006,424.0,85.0,10,0,NaT,NaN,<NA>,<NA>,341,This is our home and therefore we ask that you...
46956,26935135,Master Room in FiDi - Private Bathroom,31349183428,unconfirmed,Olivia,Manhattan,Financial District,40.70612,-74.00464,United States,US,True,moderate,Private room,2009,848.0,170.0,1,0,NaT,NaN,<NA>,<NA>,83,"No smoking, drugs, lighting candles, or campfi..."
46959,26936792,Cute & Cozy studio in Prospect Park,21945954123,unconfirmed,Jacqueline,Brooklyn,Park Slope,40.66993,-73.97709,United States,US,False,moderate,Entire home/apt,2010,846.0,169.0,11,0,NaT,NaN,<NA>,<NA>,25,Be respectful of house and neighbors on second...
46961,26937896,Private Room in Ground Floor Apt w/Backyard ac...,71263059863,verified,Eb,Manhattan,East Harlem,40.80857,-73.93951,United States,US,False,moderate,Private room,2022,317.0,63.0,1,0,NaT,NaN,<NA>,<NA>,102,Relatively quiet after 10 in the evening.
75220,42545342,habitacion con entrada privada a 20 min de manhat,65027884182,verified,Carolina,Brooklyn,Bushwick,40.70083,-73.91220,United States,US,False,strict,Private room,2007,292.0,58.0,2,0,NaT,NaN,<NA>,2,125,NaN
90419,50939750,South Slope Brooklyn Apartment!,13543109516,unconfirmed,Saquib,Brooklyn,Sunset Park,40.66033,-73.99623,United States,US,True,strict,Entire home/apt,2021,1118.0,224.0,2,0,NaT,NaN,<NA>,1,0,NaN
90635,51059047,GREAT sunny 1 bedroom,68402412887,verified,Andy,Manhattan,East Village,40.72807,-73.97718,United States,US,False,strict,Entire home/apt,2022,1122.0,224.0,5,0,NaT,NaN,<NA>,<NA>,0,All guests are expected to be respectful and m...
90636,51059599,"East 29th Street, Luxury 1bd",17950176885,unconfirmed,Ken,Manhattan,Midtown,40.74593,-73.98687,United States,US,False,flexible,Entire home/apt,2015,1102.0,220.0,30,0,NaT,NaN,<NA>,<NA>,365,• Check-in time is 4PM. Occassional Get-togeth...
90675,51081139,"Private Bedroom in Bushwick, BK",82475603637,unconfirmed,Cameron,Brooklyn,Bushwick,40.69487,-73.92630,United States,US,True,strict,Private room,2016,727.0,145.0,10,0,NaT,NaN,<NA>,<NA>,0,Respect yourself respect others please clean u...
99689,56059571,Large modern one bedroom apartment,82539184022,unconfirmed,Aliya,Manhattan,East Harlem,40.78982,-73.94263,United States,US,True,moderate,Entire home/apt,2014,481.0,96.0,7,0,NaT,NaN,<NA>,<NA>,0,NaN

In [50]:
df[
    df["neighbourhood_group"].isna() |
    df["neighbourhood"].isna()
]

# Buradaki null değerlere baktığımızda; neighbourhood_group'ı boş olanların neighbourhood'ının dolu,
# neighbourhood'ı dolu olanların ise neighbourhood_group'ının boş olduğunu görüyoruz. 
# Bu nedenle, boşlukları sağlıklıca doldurabilecek miyiz diye bakacağız.

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules
74,1042206,"HARLEM, NEW YORK WELCOMES YOU!!",98195975718,NaN,Violet,NaN,Washington Heights,40.83139,-73.94095,United States,US,True,moderate,Private room,2011,571.0,114.0,2,49,2019-06-18,1.60,2,2,<NA>,The usual courtesies apply: - No smoking - No ...
75,1042759,BLUE TRIM GUEST HOUSE,4726877402,unconfirmed,Audrey,NaN,Clinton Hill,40.68346,-73.96374,United States,US,True,strict,Private room,2014,398.0,80.0,2,105,2019-06-26,0.92,1,1,<NA>,Shoes off please Cat can go in or out as he de...
76,1043311,Charming East Village One Bedroom Flat,74322993447,verified,Violet,NaN,East Village,40.72828,-73.98801,United States,US,False,strict,Entire home/apt,2018,618.0,124.0,5,21,2019-01-02,0.20,4,1,<NA>,no smoking quiet
77,1043863,Manhattan Room,11468499446,verified,Sofia,NaN,Upper East Side,40.76865,-73.95058,United States,US,False,strict,Private room,2007,116.0,23.0,1,142,2019-07-06,1.50,4,1,<NA>,I'm a semi kosher vegetarian which means that ...
78,1044415,Little King of Queens,68599531533,unconfirmed,Melanie,NaN,Woodside,40.75038,-73.90334,United States,US,True,flexible,Private room,2012,54.0,11.0,30,25,NaT,0.22,2,1,<NA>,No Street Shoes allowed in House. No cooking K...
90,1051043,Cozy Bedroom in Williamsburg 3 BR,14067827221,unconfirmed,Lilianna,NaN,Williamsburg,40.71156,-73.96218,United States,US,False,moderate,Private room,2015,266.0,53.0,3,174,2019-06-22,1.54,5,4,<NA>,Dryer and Washing Machine are in Basement (1.0...
91,1051595,Sunny room+Pvte office in huge loft,12884105458,NaN,Albert,NaN,Bushwick,40.70032,-73.93830,United States,US,False,moderate,Private room,2012,728.0,146.0,4,24,NaT,0.28,5,1,<NA>,"To enjoy, relax, feel safe and cozy. Also, kee..."
92,1052148,Spacious Prospect Heights Apartment,63218812094,unconfirmed,Sarah,NaN,Prospect Heights,40.68233,-73.97261,United States,US,False,flexible,Entire home/apt,2021,583.0,117.0,4,166,2019-06-27,3.40,2,1,<NA>,We ask that guests be respectful as there are ...
148,1083076,NYC Zen,83696952551,verified,Amelia,NaN,East Village,40.72354,-73.98295,United States,US,False,strict,Entire home/apt,2003,NaN,119.0,3,30,2019-06-17,0.28,5,1,344,No Smoking No Pets No Parties
161,1090256,Indie-Chic Share In Williamsburg,1595619477,unconfirmed,Darcy,NaN,Williamsburg,40.71088,-73.95055,United States,US,<NA>,NaN,Private room,2022,1020.0,204.0,4,202,2019-05-28,1.86,5,2,<NA>,"No smoking in the apartment, even with the win..."
168,1094122,Parlor Room In Victorian Townhouse,45745264571,NaN,Heather,NaN,Clinton Hill,40.68843,-73.96408,United States,US,True,strict,Private room,2004,925.0,185.0,149,294,2019-06-24,NaN,3,3,311,NaN
196,1109587,Prime Location in Manhattan,47239505401,verified,NaN,NaN,Chelsea,40.74859,-73.99671,United States,US,True,flexible,Private room,<NA>,267.0,53.0,1,375,2019-06-18,3.52,3,1,<NA>,ANDREA'S HOUSE RULES: ** All overnight guests...
206,1115110,NaN,87631747854,NaN,Amanda,NaN,Prospect Heights,40.67870,-73.97262,United States,US,False,strict,Private room,<NA>,936.0,187.0,2,226,2019-06-06,2.12,4,3,263,This is a non smoking house. Quiet hours are ...
241,1134440,ACCOMMODATIONS GALORE #2,81849555528,verified,Richardson,NaN,East Harlem,40.80942,-73.93936,United States,US,False,flexible,Entire home/apt,<NA>,252.0,50.0,3,135,2019-06-20,1.30,1,3,109,I'm a semi kosher vegetarian which means that ...
249,1138859,BROWNSTONE SUNDRENCHED BEAUTY,49595827306,NaN,Richardson,NaN,Bushwick,40.68800,-73.91710,United States,US,True,moderate,Entire home/apt,2022,1028.0,206.0,3,111,NaT,2.13,<NA>,1,150,Please review the terms of this rental agreeme...
262,1146039,DOMINIQUE'S NY mini efficiency* wifi*metro*quiet,73292273095,verified,Hamilton,NaN,Eastchester,40.88057,-73.83572,United States,US,True,flexible,Entire home/apt,2016,909.0,182.0,2,38,2019-06-27,0.50,4,13,<NA>,Please do not let any of the animals outside! ...
295,1164265,Cozy Private Room in Apartment,11745797323,NaN,Tucker,NaN,Harlem,40.82976,-73.94867,United States,US,False,flexible,Private room,2019,960.0,192.0,30,64,2018-07-06,0.68,1,1,52,#NAME?
307,1170892,NaN,48659572099,verified,Stewart,NaN,Chinatown,40.71659,-73.98945,United States,US,True,flexible,Entire home/apt,2014,651.0,130.0,25,43,2019-06-17,0.42,5,1,87,- No shoes in apartment - No parties - Enjoy y...
319,1177520,BROOKLYN > Guest Room w/ King Bed in Williamsburg,59305845429,verified,Holmes,NaN,Williamsburg,40.71398,-73.95763,United States,US,False,strict,Private room,2017,1080.0,216.0,2,220,2019-06-22,2.17,3,2,361,NaN
361,1200716,Bienvenue,92724296556,verified,Richards,NaN,Queens Village,40.72413,-73.76133,United States,US,True,moderate,Private room,2015,671.0,134.0,1,43,2019-07-08,0.45,5,1,150,- no shoes inside - quiet after 8:30pm
384,1213419,Sun-Drenched Hamilton Hts Jewel,618609977,unconfirmed,Payne,NaN,Harlem,40.82399,-73.95328,United States,US,True,moderate,Private room,2013,1083.0,217.0,14,35,2019-06-01,0.35,5,1,61,I feel very responsible and accountable for yo...
415,1230541,Truly Amazing Oasis In The City,65344662582,unconfirmed,Heather,NaN,Williamsburg,40.71363,-73.96019,United States,US,True,strict,Entire home/apt,2022,852.0,170.0,3,150,2019-07-05,1.55,3,1,<NA>,NaN
448,1248766,Hancock Town House!-Stuyvesant Mews,17302896128,unconfirmed,Lucia,NaN,Bedford-Stuyvesant,40.68669,-73.91989,United States,US,False,moderate,Private room,2013,999.0,200.0,1,27,2017-10-08,0.28,1,4,181,NaN
465,1258156,☆ STUDIO East Village ☆ Own bath! ☆ Sleeps 4 ☆,87134189711,NaN,Alan,NaN,East Village,40.72636,-73.98917,United States,US,True,strict,Entire home/apt,<NA>,515.0,103.0,2,280,2019-07-05,2.92,1,3,94,NaN
488,1270858,The Happy home!,91709093046,verified,Eddy,NaN,East Harlem,40.79320,-73.94007,United States,US,False,strict,Entire home/apt,2007,1133.0,227.0,2,15,2016-02-15,0.16,<NA>,1,326,Please remember that this is a residential bui...
492,1273068,Large Quiet Bedroom Near Columbia U,95738430033,verified,Rebecca,NaN,Harlem,40.80518,-73.95359,United States,US,False,strict,Private room,2016,945.0,189.0,5,43,2018-01-03,0.47,3,2,147,NaN
517,1286875,"""The Oasis"" on Bedford Williamsburg",30603782652,unconfirmed,Lucas,Brooklyn,NaN,40.71580,-73.95803,United States,US,<NA>,NaN,Entire home/apt,2005,NaN,130.0,6,1,2016-01-01,0.02,5,1,266,1. No parties. 2. Respect the neighbors. Nois...
547,1303444,STYLISH EAST VILLAGE FLAT,6825076306,verified,Arnold,Manhattan,NaN,40.73089,-73.98195,United States,US,True,strict,Entire home/apt,2013,749.0,150.0,30,25,2018-04-30,0.26,4,1,67,NaN
575,1318909,"2 Bed, 2 Bath Apartment on Central Park West",86633710982,unconfirmed,Arthur,Manhattan,NaN,40.79816,-73.96190,United States,US,True,strict,Entire home/apt,2014,892.0,178.0,2,45,2019-04-22,0.47,4,3,4,NaN
589,1326641,CBG Helps Haiti Rm #3,33952991254,verified,Jacob,Brooklyn,NaN,40.68012,-73.97847,United States,US,False,strict,Private room,2003,793.0,159.0,2,23,2018-09-15,0.24,1,6,<NA>,Please remember that this is a residential bui...
613,1339896,Wonderfully inviting East Village,84560895335,verified,Carter,Manhattan,NaN,40.72709,-73.98274,United States,US,True,moderate,Private room,2004,486.0,97.0,1,109,2015-10-02,1.15,2,1,116,#NAME?
624,1345971,Stylish Studio with exclusive Terrace,21547822804,unconfirmed,Cole,Manhattan,NaN,40.75348,-73.97065,United States,US,False,moderate,Entire home/apt,2019,417.0,83.0,30,136,2019-06-19,1.45,4,1,272,Please remember that this is a residential bui...
633,1350942,Lower East Side/Chinatown 1 Bedroom,58408401042,verified,Higgins,Manhattan,NaN,40.71693,-73.98948,United States,US,False,flexible,Entire home/apt,2017,1148.0,230.0,5,8,2018-05-18,0.11,3,1,42,NaN
643,1356465,2BR Apt - 20min to Soho,21192497123,verified,Barrett,Brooklyn,NaN,40.68016,-73.94878,United States,US,False,moderate,Entire home/apt,2015,938.0,188.0,3,5,2017-07-09,0.05,2,1,<NA>,Smoking is allowed on the patio only. No pets ...
670,1371377,Loft Suite @ The Box House Hotel,75427375884,verified,Gray,Brooklyn,NaN,40.73641,-73.95330,United States,US,False,strict,Entire home/apt,2006,104.0,21.0,3,24,2018-11-06,0.32,4,28,<NA>,NaN
678,1375795,Loft Suite @ The Box House Hotel,34416621424,verified,Smith,Brooklyn,NaN,40.73693,-73.95316,United States,US,<NA>,NaN,Entire home/apt,2018,914.0,183.0,3,30,2019-07-03,0.32,5,28,296,House Rules Welcome to Boston-Furnished-Rental...
681,1377452,Loft w/ Terrace @ Box House Hotel,77372797211,unconfirmed,Higgins,Brooklyn,NaN,40.73783,-73.95259,United States,US,True,flexible,Private room,2009,528.0,106.0,3,3,2015-11-03,0.03,2,28,216,PLEASE NOTE: • 6.25% MA State Sales Tax is al...
726,1402306,Studio sublet in Hell's kitchen,42150054304,verified,Baker,Manhattan,NaN,40.76217,-73.98411,United States,US,True,moderate,Entire home/apt,2003,831.0,166.0,5,8,2015-01-08,0.09,3,1,322,Please Note: This unit was just renovated in A...
731,1405067,One bed suite with private garden,464927437,unconfirmed,Myers,Manhattan,NaN,40.78304,-73.97447,United States,US,False,flexible,Entire home/apt,2005,624.0,125.0,30,16,2019-03-31,0.17,4,5,24,"No smoking, no pets, no parties please. Respec..."
760,1421084,Spacious room on charming block in Greenpoint!,67988523719,verified,Williams,Brooklyn,NaN,40.72723,-73.95728,United States,US,True,strict,Private room,2020,745.0,149.0,4,6,2019-04-21,0.07,3,1,20,NaN
770,1426607,Nights in White Satin in the Slope,54377094483,unconfirmed,Farrell,Brooklyn,NaN,40.65992,-73.99042,United States,US,False,strict,Entire home/apt,2007,1111.0,222.0,180,1,2016-09-01,0.03,4,1,163,NaN
40383,23304867,2000 sq ft Unique Cozy Art Home with Private Room,57604959046,unconfirmed,Angeline,NaN,Bushwick,40.69085,-73.90937,United States,US,False,flexible,Private room,2011,312.0,62.0,1,0,NaT,NaN,4,1,269,NaN
40396,23312047,Large room near express trains & Central Park,22672807843,unconfirmed,Julian,NaN,Upper West Side,40.79471,-73.96918,United States,US,False,moderate,Private room,2012,175.0,35.0,4,2,2019-02-22,0.37,2,1,0,No pets. No smoking. Please :)

In [51]:
# We are performing a null value inspection for the 'neighbourhood' and 'neighbourhood_group' columns.
# This code displays the mapping between each 'neighbourhood' and its corresponding 'neighbourhood_group';

df.groupby("neighbourhood")["neighbourhood_group"].unique()

neighbourhood
Allerton                                         [Bronx]
Arden Heights                            [Staten Island]
Arrochar                                 [Staten Island]
Arverne                                         [Queens]
Astoria                                         [Queens]
Bath Beach                                    [Brooklyn]
Battery Park City                            [Manhattan]
Bay Ridge                                     [Brooklyn]
Bay Terrace                                     [Queens]
Bay Terrace, Staten Island               [Staten Island]
Baychester                                       [Bronx]
Bayside                                         [Queens]
Bayswater                                       [Queens]
Bedford-Stuyvesant                       [Brooklyn, nan]
Belle Harbor                                    [Queens]
Bellerose                                       [Queens]
Belmont                                          [Bronx]
Bensonhurst                                   [Brooklyn]
Bergen Beach                                  [Brooklyn]
Boerum Hill                                   [Brooklyn]
Borough Park                                  [Brooklyn]
Breezy Point                                    [Queens]
Briarwood                                       [Queens]
Brighton Beach                                [Brooklyn]
Bronxdale                                        [Bronx]
Brooklyn Heights                              [Brooklyn]
Brownsville                                   [Brooklyn]
Bull's Head                              [Staten Island]
Bushwick                                 [Brooklyn, nan]
Cambria Heights                                 [Queens]
Canarsie                                      [Brooklyn]
Carroll Gardens                               [Brooklyn]
Castle Hill                                      [Bronx]
Castleton Corners                        [Staten Island]
Chelsea                       [manhatan, Manhattan, nan]
Chelsea, Staten Island                   [Staten Island]
Chinatown                               [Manhattan, nan]
City Island                                      [Bronx]
Civic Center                                 [Manhattan]
Claremont Village                                [Bronx]
Clason Point                                     [Bronx]
Clifton                                  [Staten Island]
Clinton Hill                             [Brooklyn, nan]
Co-op City                                       [Bronx]
Cobble Hill                                   [Brooklyn]
College Point                                   [Queens]
Columbia St                                   [Brooklyn]
Concord                                  [Staten Island]
Concourse                                        [Bronx]
Concourse Village                                [Bronx]
Coney Island                                  [Brooklyn]
Corona                                          [Queens]
Crown Heights                                 [Brooklyn]
Cypress Hills                                 [Brooklyn]
DUMBO                                         [Brooklyn]
Ditmars Steinway                                [Queens]
Dongan Hills                             [Staten Island]
Douglaston                                      [Queens]
Downtown Brooklyn                             [Brooklyn]
Dyker Heights                                 [Brooklyn]
East Elmhurst                                   [Queens]
East Flatbush                                 [Brooklyn]
East Harlem                             [Manhattan, nan]
East Morrisania                                  [Bronx]
East New York                                 [Brooklyn]
East Village                            [Manhattan, nan]
Eastchester                                 [nan, Bronx]
Edenwald                                         [Bronx]
Edgemere                                        [Queens]
Elmhurst                                        [Queens]
Eltingville                              [Staten Island]
Emerson Hill                             [Staten Island]
Far Rockaway                                    [Queens]
Fieldston                                        [Bronx]
Financial District                           [Manhattan]
Flatbush                                      [Brooklyn]
Flatiron District                            [Manhattan]
Flatlands                                     [Brooklyn]
Flushing                                        [Queens]
Fordham                                          [Bronx]
Forest Hills                                    [Queens]
Fort Greene                                   [Brooklyn]
Fort Hamilton                                 [Brooklyn]
Fort Wadsworth                           [Staten Island]
Fresh Meadows                                   [Queens]
Gerritsen Beach                               [Brooklyn]
Glen Oaks                                       [Queens]
Glendale                                        [Queens]
Gowanus                                       [Brooklyn]
Gramercy                                     [Manhattan]
Graniteville                             [Staten Island]
Grant City                               [Staten Island]
Gravesend                                     [Brooklyn]
Great Kills                              [Staten Island]
Greenpoint                                    [Brooklyn]
Greenwich Village                            [Manhattan]
Grymes Hill                              [Staten Island]
Harlem                                  [Manhattan, nan]
Hell's Kitchen                               [Manhattan]
Highbridge                                       [Bronx]
Hollis                                          [Queens]
Holliswood                                      [Queens]
Howard Beach                                    [Queens]
Howland Hook                             [Staten Island]
Huguenot                                 [Staten Island]
Hunts Point                                      [Bronx]
Inwood                                       [Manhattan]
Jackson Heights                                 [Queens]
Jamaica                                         [Queens]
Jamaica Estates                                 [Queens]
Jamaica Hills                                   [Queens]
Kensington                                    [Brooklyn]
Kew Gardens                                     [Queens]
Kew Gardens Hills                               [Queens]
Kingsbridge                                      [Bronx]
Kips Bay                                     [Manhattan]
Laurelton                                       [Queens]
Lighthouse Hill                          [Staten Island]
Little Italy                                 [Manhattan]
Little Neck                                     [Queens]
Long Island City                                [Queens]
Longwood                                         [Bronx]
Lower East Side                              [Manhattan]
Manhattan Beach                               [Brooklyn]
Marble Hill                                  [Manhattan]
Mariners Harbor                          [Staten Island]
Maspeth                                         [Queens]
Melrose                                          [Bronx]
Middle Village                                  [Queens]
Midland Beach                            [Staten Island]
Midtown                                      [Manhattan]
Midwood                                       [Brooklyn]
Mill Basin                                    [Brooklyn]
Morningside Heights                          [Manhattan]
Morris Heights                                   [Bronx]
Morris Park                                      [Bronx]
Morrisania                                       [Bronx]
Mott Haven                                       [Bronx]
Mount Eden                                       [Bronx]
Mount Hope                                       [Bronx]
Murray Hill                                  [Manhattan]
Navy Yard                                     [Brooklyn]
Neponsit                                        [Queens]
New Brighton                             [Staten Island]
New Dorp                                 [Staten Island]
New Dorp Beach                           [Staten Island]
New Springville                          [Staten Island]
NoHo                                         [Manhattan]
Nolita                                       [Manhattan]
North Riverdale                                  [Bronx]
Norwood                                          [Bronx]
Oakwood                                  [Staten Island]
Olinville                                        [Bronx]
Ozone Park                                      [Queens]
Park Slope                                    [Brooklyn]
Parkchester                                      [Bronx]
Pelham Bay                                       [Bronx]
Pelham Gardens                                   [Bronx]
Port Morris                                      [Bronx]
Port Richmond                            [Staten Island]
Prince's Bay                             [Staten Island]
Prospect Heights                         [Brooklyn, nan]
Prospect-Lefferts Gardens                     [Brooklyn]
Queens Village                             [nan, Queens]
Randall Manor                            [Staten Island]
Red Hook                                      [Brooklyn]
Rego Park                                       [Queens]
Richmond Hill                                   [Queens]
Richmondtown                             [Staten Island]
Ridgewood                                       [Queens]
Riverdale                                        [Bronx]
Rockaway Beach                                  [Queens]
Roosevelt Island                             [Manhattan]
Rosebank                                 [Staten Island]
Rosedale                                        [Queens]
Rossville                                [Staten Island]
Schuylerville                                    [Bronx]
Sea Gate                                      [Brooklyn]
Sheepshead Bay                                [Brooklyn]
Shore Acres                              [Staten Island]
Silver Lake                              [Staten Island]
SoHo                                         [Manhattan]
Soundview                                        [Bronx]
South Beach                              [Staten Island]
South Ozone Park                                [Queens]
South Slope                          [brookln, Brooklyn]
Springfield Gardens                             [Queens]
Spuyten Duyvil                                   [Bronx]
St. Albans                                      [Queens]
St. George                               [Staten Island]
Stapleton                                [Staten Island]
Stuyvesant Town                              [Manhattan]
Sunnyside                                       [Queens]
Sunset Park                                   [Brooklyn]
Theater District                             [Manhattan]
Throgs Neck                                      [Bronx]
Todt Hill                                [Staten Island]
Tompkinsville                            [Staten Island]
Tottenville                              [Staten Island]
Tremont                                          [Bronx]
Tribeca                                      [Manhattan]
Two Bridges                                  [Manhattan]
Unionport                                        [Bronx]
University Heights                               [Bronx]
Upper East Side                         [Manhattan, nan]
Upper West Side                         [Manhattan, nan]
Van Nest                                         [Bronx]
Vinegar Hill                                  [Brooklyn]
Wakefield                                        [Bronx]
Washington Heights                      [nan, Manhattan]
West Brighton                            [Staten Island]
West Farms                                       [Bronx]
West Village                                 [Manhattan]
Westchester Square                               [Bronx]
Westerleigh                              [Staten Island]
Whitestone                                      [Queens]
Williamsbridge                                   [Bronx]
Williamsburg                             [Brooklyn, nan]
Willowbrook                              [Staten Island]
Windsor Terrace                               [Brooklyn]
Woodhaven                                       [Queens]
Woodlawn                                         [Bronx]
Woodrow                                  [Staten Island]
Woodside                                   [nan, Queens]
Name: neighbourhood_group, dtype: object

In [52]:
df.groupby("neighbourhood")["neighbourhood_group"].nunique().sort_values(ascending=False)

# To guarantee that missing geographic attributes can be imputed deterministically, 
# we evaluate the mapping cardinality between neighbourhood and neighbourhood_group. 
# The diagnostic shows that every neighbourhood belongs to a single, unique group—with the exception of Chelsea and South Slope, 
# which span multiple boundaries.

neighbourhood
Chelsea                       2
South Slope                   2
Arrochar                      1
Allerton                      1
Astoria                       1
Bath Beach                    1
Battery Park City             1
Arden Heights                 1
Bay Terrace                   1
Bay Terrace, Staten Island    1
Baychester                    1
Bayside                       1
Bayswater                     1
Bedford-Stuyvesant            1
Belle Harbor                  1
Arverne                       1
Belmont                       1
Bensonhurst                   1
Bergen Beach                  1
Boerum Hill                   1
Borough Park                  1
Breezy Point                  1
Briarwood                     1
Brighton Beach                1
Bronxdale                     1
Brooklyn Heights              1
Brownsville                   1
Bull's Head                   1
Bushwick                      1
Cambria Heights               1
Canarsie                      1
Bay Ridge                     1
Carroll Gardens               1
Castle Hill                   1
Castleton Corners             1
Chelsea, Staten Island        1
Chinatown                     1
City Island                   1
Civic Center                  1
Claremont Village             1
Clason Point                  1
Clifton                       1
Clinton Hill                  1
Co-op City                    1
Cobble Hill                   1
College Point                 1
Columbia St                   1
Concord                       1
Concourse                     1
Concourse Village             1
Coney Island                  1
Corona                        1
Crown Heights                 1
Cypress Hills                 1
DUMBO                         1
Ditmars Steinway              1
Dongan Hills                  1
Douglaston                    1
Downtown Brooklyn             1
Dyker Heights                 1
East Elmhurst                 1
East Flatbush                 1
East Harlem                   1
East Morrisania               1
East New York                 1
East Village                  1
Eastchester                   1
Edenwald                      1
Edgemere                      1
Elmhurst                      1
Eltingville                   1
Emerson Hill                  1
Far Rockaway                  1
Fieldston                     1
Financial District            1
Flatbush                      1
Flatiron District             1
Flatlands                     1
Flushing                      1
Fordham                       1
Forest Hills                  1
Fort Greene                   1
Fort Hamilton                 1
Fort Wadsworth                1
Fresh Meadows                 1
Gerritsen Beach               1
Glen Oaks                     1
Glendale                      1
Gowanus                       1
Gramercy                      1
Graniteville                  1
Grant City                    1
Gravesend                     1
Great Kills                   1
Greenpoint                    1
Bellerose                     1
Greenwich Village             1
Grymes Hill                   1
Hell's Kitchen                1
Harlem                        1
Hollis                        1
Holliswood                    1
Howard Beach                  1
Highbridge                    1
Huguenot                      1
Hunts Point                   1
Inwood                        1
Jackson Heights               1
Jamaica                       1
Jamaica Estates               1
Jamaica Hills                 1
Howland Hook                  1
Kew Gardens                   1
Kew Gardens Hills             1
Kingsbridge                   1
Kips Bay                      1
Laurelton                     1
Lighthouse Hill               1
Little Italy                  1
Little Neck                   1
Long Island City              1
Longwood                      1
Lower East Side               1
Manhattan Beach               1
Marble Hill                   1
Mariners Harbor               1
Maspeth                       1
Kensington                    1
Middle Village                1
Midland Beach                 1
Midtown                       1
Midwood                       1
Mill Basin                    1
Morningside Heights           1
Morris Heights                1
Morris Park                   1
Morrisania                    1
Mott Haven                    1
Mount Eden                    1
Mount Hope                    1
Murray Hill                   1
Navy Yard                     1
Neponsit                      1
New Brighton                  1
New Dorp                      1
New Dorp Beach                1
New Springville               1
NoHo                          1
Nolita                        1
North Riverdale               1
Norwood                       1
Oakwood                       1
Olinville                     1
Ozone Park                    1
Park Slope                    1
Parkchester                   1
Pelham Bay                    1
Pelham Gardens                1
Port Morris                   1
Melrose                       1
Port Richmond                 1
Prince's Bay                  1
Prospect-Lefferts Gardens     1
Prospect Heights              1
Randall Manor                 1
Red Hook                      1
Rego Park                     1
Queens Village                1
Richmondtown                  1
Ridgewood                     1
Riverdale                     1
Rockaway Beach                1
Roosevelt Island              1
Rosebank                      1
Rosedale                      1
Richmond Hill                 1
Rossville                     1
Schuylerville                 1
Sheepshead Bay                1
Sea Gate                      1
Silver Lake                   1
SoHo                          1
Soundview                     1
Shore Acres                   1
South Beach                   1
South Ozone Park              1
Springfield Gardens           1
Spuyten Duyvil                1
St. Albans                    1
St. George                    1
Stapleton                     1
Stuyvesant Town               1
Sunnyside                     1
Sunset Park                   1
Theater District              1
Throgs Neck                   1
Todt Hill                     1
Tompkinsville                 1
Tottenville                   1
Tremont                       1
Tribeca                       1
Two Bridges                   1
Unionport                     1
University Heights            1
Upper East Side               1
Upper West Side               1
Van Nest                      1
Vinegar Hill                  1
Wakefield                     1
Washington Heights            1
West Brighton                 1
West Farms                    1
West Village                  1
Westchester Square            1
Westerleigh                   1
Whitestone                    1
Williamsbridge                1
Williamsburg                  1
Willowbrook                   1
Windsor Terrace               1
Woodhaven                     1
Woodlawn                      1
Woodrow                       1
Woodside                      1
Name: neighbourhood_group, dtype: int64

In [53]:
df[df["neighbourhood"] == "Chelsea"]["neighbourhood_group"].unique()

array(['manhatan', 'Manhattan', nan], dtype=object)

In [54]:
df[df["neighbourhood"] == "South Slope"]["neighbourhood_group"].unique()

# Upon closer inspection, both actually belong to a single group, 
# but they appeared distinct due to typos/formatting inconsistencies.

array(['brookln', 'Brooklyn'], dtype=object)

In [55]:
df["neighbourhood_group"] = df["neighbourhood_group"].replace({
    "brookln": "Brooklyn",
    "manhatan": "Manhattan"
})

# Standardizing string formats to correct typos and spacing inconsistencies.

In [56]:
df[df["neighbourhood_group"].isna()]["neighbourhood"].map(
    df.groupby("neighbourhood")["neighbourhood_group"].first()
)

# Here, for rows with a missing 'neighbourhood_group', we impute the value 
# by referencing the 'neighbourhood_group' associated with the same 'neighbourhood' in other rows.

74       Manhattan
75        Brooklyn
76       Manhattan
77       Manhattan
78          Queens
90        Brooklyn
91        Brooklyn
92        Brooklyn
148      Manhattan
161       Brooklyn
168       Brooklyn
196      Manhattan
206       Brooklyn
241      Manhattan
249       Brooklyn
262          Bronx
295      Manhattan
307      Manhattan
319       Brooklyn
361         Queens
384      Manhattan
415       Brooklyn
448       Brooklyn
465      Manhattan
488      Manhattan
492      Manhattan
40383     Brooklyn
40396    Manhattan
Name: neighbourhood, dtype: object

In [57]:
df.groupby("neighbourhood")["neighbourhood_group"].unique()

neighbourhood
Allerton                               [Bronx]
Arden Heights                  [Staten Island]
Arrochar                       [Staten Island]
Arverne                               [Queens]
Astoria                               [Queens]
Bath Beach                          [Brooklyn]
Battery Park City                  [Manhattan]
Bay Ridge                           [Brooklyn]
Bay Terrace                           [Queens]
Bay Terrace, Staten Island     [Staten Island]
Baychester                             [Bronx]
Bayside                               [Queens]
Bayswater                             [Queens]
Bedford-Stuyvesant             [Brooklyn, nan]
Belle Harbor                          [Queens]
Bellerose                             [Queens]
Belmont                                [Bronx]
Bensonhurst                         [Brooklyn]
Bergen Beach                        [Brooklyn]
Boerum Hill                         [Brooklyn]
Borough Park                        [Brooklyn]
Breezy Point                          [Queens]
Briarwood                             [Queens]
Brighton Beach                      [Brooklyn]
Bronxdale                              [Bronx]
Brooklyn Heights                    [Brooklyn]
Brownsville                         [Brooklyn]
Bull's Head                    [Staten Island]
Bushwick                       [Brooklyn, nan]
Cambria Heights                       [Queens]
Canarsie                            [Brooklyn]
Carroll Gardens                     [Brooklyn]
Castle Hill                            [Bronx]
Castleton Corners              [Staten Island]
Chelsea                       [Manhattan, nan]
Chelsea, Staten Island         [Staten Island]
Chinatown                     [Manhattan, nan]
City Island                            [Bronx]
Civic Center                       [Manhattan]
Claremont Village                      [Bronx]
Clason Point                           [Bronx]
Clifton                        [Staten Island]
Clinton Hill                   [Brooklyn, nan]
Co-op City                             [Bronx]
Cobble Hill                         [Brooklyn]
College Point                         [Queens]
Columbia St                         [Brooklyn]
Concord                        [Staten Island]
Concourse                              [Bronx]
Concourse Village                      [Bronx]
Coney Island                        [Brooklyn]
Corona                                [Queens]
Crown Heights                       [Brooklyn]
Cypress Hills                       [Brooklyn]
DUMBO                               [Brooklyn]
Ditmars Steinway                      [Queens]
Dongan Hills                   [Staten Island]
Douglaston                            [Queens]
Downtown Brooklyn                   [Brooklyn]
Dyker Heights                       [Brooklyn]
East Elmhurst                         [Queens]
East Flatbush                       [Brooklyn]
East Harlem                   [Manhattan, nan]
East Morrisania                        [Bronx]
East New York                       [Brooklyn]
East Village                  [Manhattan, nan]
Eastchester                       [nan, Bronx]
Edenwald                               [Bronx]
Edgemere                              [Queens]
Elmhurst                              [Queens]
Eltingville                    [Staten Island]
Emerson Hill                   [Staten Island]
Far Rockaway                          [Queens]
Fieldston                              [Bronx]
Financial District                 [Manhattan]
Flatbush                            [Brooklyn]
Flatiron District                  [Manhattan]
Flatlands                           [Brooklyn]
Flushing                              [Queens]
Fordham                                [Bronx]
Forest Hills                          [Queens]
Fort Greene                         [Brooklyn]
Fort Hamilton                       [Brooklyn]
Fort Wadsworth                 [Staten Island]
Fresh Meadows                         [Queens]
Gerritsen Beach                     [Brooklyn]
Glen Oaks                             [Queens]
Glendale                              [Queens]
Gowanus                             [Brooklyn]
Gramercy                           [Manhattan]
Graniteville                   [Staten Island]
Grant City                     [Staten Island]
Gravesend                           [Brooklyn]
Great Kills                    [Staten Island]
Greenpoint                          [Brooklyn]
Greenwich Village                  [Manhattan]
Grymes Hill                    [Staten Island]
Harlem                        [Manhattan, nan]
Hell's Kitchen                     [Manhattan]
Highbridge                             [Bronx]
Hollis                                [Queens]
Holliswood                            [Queens]
Howard Beach                          [Queens]
Howland Hook                   [Staten Island]
Huguenot                       [Staten Island]
Hunts Point                            [Bronx]
Inwood                             [Manhattan]
Jackson Heights                       [Queens]
Jamaica                               [Queens]
Jamaica Estates                       [Queens]
Jamaica Hills                         [Queens]
Kensington                          [Brooklyn]
Kew Gardens                           [Queens]
Kew Gardens Hills                     [Queens]
Kingsbridge                            [Bronx]
Kips Bay                           [Manhattan]
Laurelton                             [Queens]
Lighthouse Hill                [Staten Island]
Little Italy                       [Manhattan]
Little Neck                           [Queens]
Long Island City                      [Queens]
Longwood                               [Bronx]
Lower East Side                    [Manhattan]
Manhattan Beach                     [Brooklyn]
Marble Hill                        [Manhattan]
Mariners Harbor                [Staten Island]
Maspeth                               [Queens]
Melrose                                [Bronx]
Middle Village                        [Queens]
Midland Beach                  [Staten Island]
Midtown                            [Manhattan]
Midwood                             [Brooklyn]
Mill Basin                          [Brooklyn]
Morningside Heights                [Manhattan]
Morris Heights                         [Bronx]
Morris Park                            [Bronx]
Morrisania                             [Bronx]
Mott Haven                             [Bronx]
Mount Eden                             [Bronx]
Mount Hope                             [Bronx]
Murray Hill                        [Manhattan]
Navy Yard                           [Brooklyn]
Neponsit                              [Queens]
New Brighton                   [Staten Island]
New Dorp                       [Staten Island]
New Dorp Beach                 [Staten Island]
New Springville                [Staten Island]
NoHo                               [Manhattan]
Nolita                             [Manhattan]
North Riverdale                        [Bronx]
Norwood                                [Bronx]
Oakwood                        [Staten Island]
Olinville                              [Bronx]
Ozone Park                            [Queens]
Park Slope                          [Brooklyn]
Parkchester                            [Bronx]
Pelham Bay                             [Bronx]
Pelham Gardens                         [Bronx]
Port Morris                            [Bronx]
Port Richmond                  [Staten Island]
Prince's Bay                   [Staten Island]
Prospect Heights               [Brooklyn, nan]
Prospect-Lefferts Gardens           [Brooklyn]
Queens Village                   [nan, Queens]
Randall Manor                  [Staten Island]
Red Hook                            [Brooklyn]
Rego Park                             [Queens]
Richmond Hill                         [Queens]
Richmondtown                   [Staten Island]
Ridgewood                             [Queens]
Riverdale                              [Bronx]
Rockaway Beach                        [Queens]
Roosevelt Island                   [Manhattan]
Rosebank                       [Staten Island]
Rosedale                              [Queens]
Rossville                      [Staten Island]
Schuylerville                          [Bronx]
Sea Gate                            [Brooklyn]
Sheepshead Bay                      [Brooklyn]
Shore Acres                    [Staten Island]
Silver Lake                    [Staten Island]
SoHo                               [Manhattan]
Soundview                              [Bronx]
South Beach                    [Staten Island]
South Ozone Park                      [Queens]
South Slope                         [Brooklyn]
Springfield Gardens                   [Queens]
Spuyten Duyvil                         [Bronx]
St. Albans                            [Queens]
St. George                     [Staten Island]
Stapleton                      [Staten Island]
Stuyvesant Town                    [Manhattan]
Sunnyside                             [Queens]
Sunset Park                         [Brooklyn]
Theater District                   [Manhattan]
Throgs Neck                            [Bronx]
Todt Hill                      [Staten Island]
Tompkinsville                  [Staten Island]
Tottenville                    [Staten Island]
Tremont                                [Bronx]
Tribeca                            [Manhattan]
Two Bridges                        [Manhattan]
Unionport                              [Bronx]
University Heights                     [Bronx]
Upper East Side               [Manhattan, nan]
Upper West Side               [Manhattan, nan]
Van Nest                               [Bronx]
Vinegar Hill                        [Brooklyn]
Wakefield                              [Bronx]
Washington Heights            [nan, Manhattan]
West Brighton                  [Staten Island]
West Farms                             [Bronx]
West Village                       [Manhattan]
Westchester Square                     [Bronx]
Westerleigh                    [Staten Island]
Whitestone                            [Queens]
Williamsbridge                         [Bronx]
Williamsburg                   [Brooklyn, nan]
Willowbrook                    [Staten Island]
Windsor Terrace                     [Brooklyn]
Woodhaven                             [Queens]
Woodlawn                               [Bronx]
Woodrow                        [Staten Island]
Woodside                         [nan, Queens]
Name: neighbourhood_group, dtype: object

In [58]:
df["neighbourhood_group"] = df["neighbourhood_group"].fillna(
    df.groupby("neighbourhood")["neighbourhood_group"].transform("first")
)

# Here we impute missing values:
# As established previously, every 'neighbourhood' maps to a specific 'neighbourhood_group' (though some contain nulls).
# This code retrieves the first non-null group value for each neighborhood name
# and uses it to fill the corresponding NaN entries in 'neighbourhood_group'.

In [59]:
df["neighbourhood_group"].isna().sum()

np.int64(0)

In [60]:
df.isnull().sum()

id                                    0
name                                242
host_id                               0
host_identity_verified              278
host_name                           404
neighbourhood_group                   0
neighbourhood                        15
lat                                   8
long                                  8
country                               0
country_code                          0
instant_bookable                     96
cancellation_policy                  75
room_type                             0
construction_year                   202
price                               247
service_fee                         273
minimum_nights                        0
number_of_reviews                   181
last_review                       15812
reviews_per_month                 15804
review_rate_number                  305
calculated_host_listings_count      319
availability_365                   3615
house_rules                       51920
dtype: int64

In [61]:
# Next, we impute the missing values in the 'neighbourhood' column;

df[df["neighbourhood"].isna()][
    ["neighbourhood", "neighbourhood_group", "lat", "long"]
]

# For the rows with missing 'neighbourhood' values, we examined the remaining features to see if any inferences could be made.
# As it turns out, all other columns for these rows are completely filled.

    neighbourhood neighbourhood_group       lat      long
517           NaN            Brooklyn  40.71580 -73.95803
547           NaN           Manhattan  40.73089 -73.98195
575           NaN           Manhattan  40.79816 -73.96190
589           NaN            Brooklyn  40.68012 -73.97847
613           NaN           Manhattan  40.72709 -73.98274
624           NaN           Manhattan  40.75348 -73.97065
633           NaN           Manhattan  40.71693 -73.98948
643           NaN            Brooklyn  40.68016 -73.94878
670           NaN            Brooklyn  40.73641 -73.95330
678           NaN            Brooklyn  40.73693 -73.95316
681           NaN            Brooklyn  40.73783 -73.95259
726           NaN           Manhattan  40.76217 -73.98411
731           NaN           Manhattan  40.78304 -73.97447
760           NaN            Brooklyn  40.72723 -73.95728
770           NaN            Brooklyn  40.65992 -73.99042

In [62]:
from sklearn.metrics import pairwise_distances

missing = df[df["neighbourhood"].isna()]

known = df[df["neighbourhood"].notna()]

for idx, row in missing.iterrows():
    distances = (
        (known["lat"] - row["lat"])**2 +
        (known["long"] - row["long"])**2
    )
    
    nearest = known.loc[distances.nsmallest(5).index,
                        ["neighbourhood", "neighbourhood_group", "lat", "long"]]
    
    print(f"\nEksik index: {idx}")
    print(nearest)

# To resolve the 16 missing neighbourhood entries, 
# we leverage spatial proximity by comparing their exact geographic coordinates (lat/long) against established neighborhood centroids. 
# With the exception of 2 boundary cases that yielded multiple close candidates, 
# all remaining locations were deterministically mapped to a single nearest neighborhood.

Eksik index: 517
      neighbourhood neighbourhood_group       lat      long
2565   Williamsburg            Brooklyn  40.71571 -73.95813
70741  Williamsburg            Brooklyn  40.71571 -73.95813
27148  Williamsburg            Brooklyn  40.71563 -73.95815
27260  Williamsburg            Brooklyn  40.71564 -73.95821
35803  Williamsburg            Brooklyn  40.71567 -73.95831

Eksik index: 547
      neighbourhood neighbourhood_group       lat      long
8669   East Village           Manhattan  40.73082 -73.98182
26115  East Village           Manhattan  40.73105 -73.98195
68634  East Village           Manhattan  40.73105 -73.98195
83279  East Village           Manhattan  40.73105 -73.98195
7466   East Village           Manhattan  40.73097 -73.98178

Eksik index: 575
         neighbourhood neighbourhood_group       lat      long
58018  Upper West Side           Manhattan  40.79830 -73.96204
60410  Upper West Side           Manhattan  40.79809 -73.96209
51343  Upper West Side           Manhattan  40.79831 -73.96174
54117  Upper West Side           Manhattan  40.79800 -73.96174
22388  Upper West Side           Manhattan  40.79795 -73.96199

Eksik index: 589
      neighbourhood neighbourhood_group       lat      long
24       Park Slope            Brooklyn  40.68001 -73.97865
185      Park Slope            Brooklyn  40.67994 -73.97863
1784     Park Slope            Brooklyn  40.68015 -73.97800
69960    Park Slope            Brooklyn  40.68015 -73.97800
26204    Park Slope            Brooklyn  40.67963 -73.97849

Eksik index: 613
      neighbourhood neighbourhood_group       lat      long
24299  East Village           Manhattan  40.72714 -73.98279
81463  East Village           Manhattan  40.72714 -73.98279
15125  East Village           Manhattan  40.72716 -73.98264
84947  East Village           Manhattan  40.72716 -73.98264
43162  East Village           Manhattan  40.72720 -73.98288

Eksik index: 624
      neighbourhood neighbourhood_group       lat      long
49872       Midtown           Manhattan  40.75371 -73.97072
31132       Midtown           Manhattan  40.75359 -73.97028
94065       Midtown           Manhattan  40.75359 -73.97028
25872       Midtown           Manhattan  40.75310 -73.97085
68391       Midtown           Manhattan  40.75310 -73.97085

Eksik index: 633
         neighbourhood neighbourhood_group       lat      long
37566  Lower East Side           Manhattan  40.71707 -73.98931
3468   Lower East Side           Manhattan  40.71715 -73.98936
12441        Chinatown           Manhattan  40.71668 -73.98954
14594        Chinatown           Manhattan  40.71659 -73.98949
84416        Chinatown           Manhattan  40.71659 -73.98949

Eksik index: 643
            neighbourhood neighbourhood_group       lat      long
17655  Bedford-Stuyvesant            Brooklyn  40.68001 -73.94883
87477  Bedford-Stuyvesant            Brooklyn  40.68001 -73.94883
59388  Bedford-Stuyvesant            Brooklyn  40.67987 -73.94863
57181  Bedford-Stuyvesant            Brooklyn  40.68050 -73.94885
57622  Bedford-Stuyvesant            Brooklyn  40.68034 -73.94909

Eksik index: 670
      neighbourhood neighbourhood_group       lat      long
25284    Greenpoint            Brooklyn  40.73639 -73.95342
82448    Greenpoint            Brooklyn  40.73639 -73.95342
8981     Greenpoint            Brooklyn  40.73659 -73.95354
57043    Greenpoint            Brooklyn  40.73688 -73.95344
59661    Greenpoint            Brooklyn  40.73610 -73.95375

Eksik index: 678
       neighbourhood neighbourhood_group       lat      long
57052     Greenpoint            Brooklyn  40.73714 -73.95321
21391     Greenpoint            Brooklyn  40.73714 -73.95333
78555     Greenpoint            Brooklyn  40.73714 -73.95333
91213     Greenpoint            Brooklyn  40.73714 -73.95333
101478    Greenpoint            Brooklyn  40.73714 -73.95333

Eksik index: 681
      neighbourhood neighbourhood_group       lat      long
671      Greenpoint            Brooklyn  40.73794 -73.95254
39666    Greenpoint            Brooklyn  40.73787 -73.95281
10813    Greenpoint            Brooklyn  40.73747 -73.95289
72646    Greenpoint            Brooklyn  40.73747 -73.95289
322      Greenpoint            Brooklyn  40.73749 -73.95292

Eksik index: 726
          neighbourhood neighbourhood_group       lat      long
44995  Theater District           Manhattan  40.76187 -73.98413
44992  Theater District           Manhattan  40.76246 -73.98396
51079  Theater District           Manhattan  40.76222 -73.98444
44991  Theater District           Manhattan  40.76237 -73.98442
51078  Theater District           Manhattan  40.76222 -73.98448

Eksik index: 731
         neighbourhood neighbourhood_group       lat      long
1314   Upper West Side           Manhattan  40.78292 -73.97438
69490  Upper West Side           Manhattan  40.78292 -73.97438
11179  Upper West Side           Manhattan  40.78322 -73.97435
73012  Upper West Side           Manhattan  40.78322 -73.97435
5808   Upper West Side           Manhattan  40.78278 -73.97437

Eksik index: 760
      neighbourhood neighbourhood_group       lat      long
32131    Greenpoint            Brooklyn  40.72717 -73.95688
95064    Greenpoint            Brooklyn  40.72717 -73.95688
60118    Greenpoint            Brooklyn  40.72751 -73.95694
41699    Greenpoint            Brooklyn  40.72751 -73.95693
74306    Greenpoint            Brooklyn  40.72751 -73.95693

Eksik index: 770
      neighbourhood neighbourhood_group       lat      long
8795    Sunset Park            Brooklyn  40.66002 -73.99073
38053   Sunset Park            Brooklyn  40.65977 -73.99087
55024   Sunset Park            Brooklyn  40.65943 -73.99019
36683   Sunset Park            Brooklyn  40.66051 -73.99081
50928   Sunset Park            Brooklyn  40.66045 -73.98989

In [63]:
idx = 633
row = df.loc[idx]

known = df[df["neighbourhood"].notna()]

distances = (
    (known["lat"] - row["lat"])**2 +
    (known["long"] - row["long"])**2
)

known.loc[
    distances.nsmallest(15).index,
    ["neighbourhood", "neighbourhood_group", "lat", "long"]
]

# We wanted to inspect row index 633 in detail because it yielded 2 different candidate neighbourhoods.
# By analyzing its nearest 15 neighboring records, we obtained 2 distinct potential results.

         neighbourhood neighbourhood_group       lat      long
37566  Lower East Side           Manhattan  40.71707 -73.98931
3468   Lower East Side           Manhattan  40.71715 -73.98936
12441        Chinatown           Manhattan  40.71668 -73.98954
14594        Chinatown           Manhattan  40.71659 -73.98949
84416        Chinatown           Manhattan  40.71659 -73.98949
307          Chinatown           Manhattan  40.71659 -73.98945
8687   Lower East Side           Manhattan  40.71661 -73.98916
14615  Lower East Side           Manhattan  40.71713 -73.98906
84437  Lower East Side           Manhattan  40.71713 -73.98906
14773        Chinatown           Manhattan  40.71674 -73.98995
84595        Chinatown           Manhattan  40.71674 -73.98995
38340  Lower East Side           Manhattan  40.71744 -73.98957
50485        Chinatown           Manhattan  40.71643 -73.98967
571    Lower East Side           Manhattan  40.71712 -73.98898
68030        Chinatown           Manhattan  40.71667 -73.98995

In [64]:
missing = df[df["neighbourhood"].isna()]

for idx, row in missing.iterrows():
    same_location = df[
        (df["lat"] == row["lat"]) &
        (df["long"] == row["long"]) &
        (df["neighbourhood"].notna())
    ][["neighbourhood", "neighbourhood_group", "lat", "long"]]

    print(f"\nEksik index: {idx}")
    print(same_location)

# Here, we checked whether there were any exact coordinate matches for our 16 records rather than just proximity matches, 
# and found none.

Eksik index: 517
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 547
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 575
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 589
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 613
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 624
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 633
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 643
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 670
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 678
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 681
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 726
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 731
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 760
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

Eksik index: 770
Empty DataFrame
Columns: [neighbourhood, neighbourhood_group, lat, long]
Index: []

In [65]:
# Conclusion:

# We imputed the missing values in the 'neighbourhood_group' column because they could be verified 
# using the 'neighbourhood_group' information from other records belonging to the same 'neighbourhood'.

# However, for the 16 missing values in the 'neighbourhood' column, no exact matching coordinates were found. 
# We could only infer potential values based on proximity to nearest coordinates.

# To maintain data integrity and avoid introducing unverified assumptions, we chose not to impute 
# these 16 records and retained them as missing (NaN).

In [66]:
df.isnull().sum().sort_values(ascending=False)

house_rules                       51920
last_review                       15812
reviews_per_month                 15804
availability_365                   3615
host_name                           404
calculated_host_listings_count      319
review_rate_number                  305
host_identity_verified              278
service_fee                         273
price                               247
name                                242
construction_year                   202
number_of_reviews                   181
instant_bookable                     96
cancellation_policy                  75
neighbourhood                        15
long                                  8
lat                                   8
neighbourhood_group                   0
id                                    0
host_id                               0
room_type                             0
country                               0
country_code                          0
minimum_nights                        0
dtype: int64

In [67]:
df[df["lat"].isna() | df["long"].isna()]

# We will not impute these values since there are only 8 missing entries.

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules
779,1431578,"Large, furnished room in a 2 bedroom!",20368956893,unconfirmed,Gibson,Brooklyn,Crown Heights,NaN,NaN,United States,US,False,strict,Private room,<NA>,539.0,108.0,1,1,2017-03-18,0.04,2,1,41,- Weekly and monthly prices are much lower - P...
785,1434892,Authentic NY Charming Artist Loft,66486085219,unconfirmed,Bailey,Brooklyn,Greenpoint,NaN,NaN,United States,US,False,strict,Entire home/apt,2021,1058.0,212.0,5,14,2019-06-19,0.16,5,1,226,We live and let live - hoping that you'd be re...
799,1442624,Huge room with private balcony,69386945815,verified,Hunt,Manhattan,East Village,NaN,NaN,United States,US,False,flexible,Private room,2010,506.0,101.0,6,1,2013-05-06,0.01,1,1,240,Expect respect for the family and the space--t...
814,1450908,Decorators 5-Star Flat West Village,33280739304,verified,Watson,Manhattan,West Village,NaN,NaN,United States,US,True,strict,Entire home/apt,2003,381.0,76.0,20,157,2016-08-11,1.71,4,1,61,"Please keep it clean, thats all we really ask ..."
843,1466925,Nice Private Room Beauty in Queens,15305733205,verified,Roberts,Queens,Elmhurst,NaN,NaN,United States,US,True,strict,Private room,2005,224.0,45.0,1,63,2019-05-18,0.89,3,2,70,NaN
885,1490122,Cute Room in Historic Loft!,42267829819,unconfirmed,Jones,Brooklyn,Greenpoint,NaN,NaN,United States,US,True,flexible,Private room,2019,524.0,105.0,14,22,2019-05-02,0.25,1,1,266,"Pets are cool (just clean up after them!), smo..."
926,1512766,21 day Chelsea Apartment rental,10876728736,unconfirmed,Owens,Manhattan,Flatiron District,NaN,NaN,United States,US,False,strict,Private room,2020,623.0,125.0,21,0,NaT,NaN,2,1,104,NaN
986,1545904,New York City for All Seasons!,26437872336,unconfirmed,Douglas,Manhattan,Upper West Side,NaN,NaN,United States,US,True,flexible,Private room,2014,413.0,83.0,1,25,2013-06-22,0.28,2,1,259,No Smoking No Pets

In [68]:
df[df["cancellation_policy"].isna()]

# No transformation or imputation was performed.

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules
156,1087495,"Sunny, clean 1 bdrm in W. Village",75987317883,verified,James,Manhattan,West Village,40.73226,-74.00401,United States,US,<NA>,NaN,Entire home/apt,2018,738.0,148.0,45,134,NaT,1.24,3,1,<NA>,NaN
157,1088047,Great location in Williamsburg,51756716507,unconfirmed,Roman,Brooklyn,Williamsburg,40.71363,-73.96398,United States,US,<NA>,NaN,Entire home/apt,2007,1013.0,203.0,6,27,NaT,0.25,3,1,<NA>,NaN
158,1088599,Light and Airy Upper East Side 1 BDR apartment,30351473270,unconfirmed,Kellan,Manhattan,Upper East Side,40.77711,-73.95270,United States,US,<NA>,NaN,Entire home/apt,2004,464.0,93.0,4,126,NaT,1.16,1,2,280,NaN
159,1089152,Luxury Brownstone in Boerum Hill,22525653405,unconfirmed,Owen,Brooklyn,Boerum Hill,40.68559,-73.98094,United States,US,<NA>,NaN,Entire home/apt,2006,744.0,149.0,3,23,NaT,0.27,2,1,<NA>,There is no smoking in or immediately around t...
160,1089704,CENTRAL PARK LOFT all for YOU,82585795978,verified,Eddy,Manhattan,Upper East Side,40.77456,-73.95323,United States,US,<NA>,NaN,Entire home/apt,2014,764.0,153.0,1,234,2019-06-08,2.60,5,2,353,NaN
161,1090256,Indie-Chic Share In Williamsburg,1595619477,unconfirmed,Darcy,Brooklyn,Williamsburg,40.71088,-73.95055,United States,US,<NA>,NaN,Private room,2022,1020.0,204.0,4,202,2019-05-28,1.86,5,2,<NA>,"No smoking in the apartment, even with the win..."
162,1090809,"A room w/ a Manhattan view, longer stay",973585651,unconfirmed,Dominik,Queens,Sunnyside,40.74559,-73.92313,United States,US,<NA>,NaN,Private room,2018,355.0,71.0,30,28,2019-04-12,0.26,1,1,<NA>,- We have a very friendly cat and two chickens...
163,1091361,"Private, Large & Sunny 1BR w/W&D",86944769515,verified,Aldus,Brooklyn,Bedford-Stuyvesant,40.68306,-73.94659,United States,US,<NA>,NaN,Entire home/apt,2008,244.0,49.0,2,309,2019-06-22,NaN,4,2,169,"Please keep cats out of bedrooms and bathroom,..."
199,1111244,Big Room/Washer-Dryer/Wifi/AC/JMZ,43945171386,verified,NaN,Brooklyn,Bedford-Stuyvesant,40.69546,-73.93503,United States,US,<NA>,NaN,Private room,<NA>,457.0,91.0,2,11,2017-11-13,0.48,3,1,<NA>,"We try hard to make our home lovely, and ask y..."
200,1111796,cozy studio with parking spot,16211727428,unconfirmed,Dale,Queens,Middle Village,40.71722,-73.87856,United States,US,<NA>,NaN,Entire home/apt,<NA>,938.0,188.0,30,33,2015-05-09,0.31,4,5,<NA>,"Please clean after yourself, wipe spilled wate..."
201,1112348,Clean and convenient 2BR apartment,51018805199,unconfirmed,Lydia,Queens,Ridgewood,40.70234,-73.89816,United States,US,<NA>,NaN,Private room,<NA>,405.0,81.0,7,6,2015-10-08,0.06,3,5,<NA>,No smoking. Please keep cats out of bedrooms ...
202,1112901,NaN,21389589535,unconfirmed,Annabella,Queens,Middle Village,40.71546,-73.87854,United States,US,<NA>,NaN,Entire home/apt,<NA>,907.0,181.0,7,38,2019-04-27,0.38,4,5,294,Please no smoking in the house. We are quiet ...
203,1113453,NaN,80926683538,NaN,Cherry,Brooklyn,Williamsburg,40.71950,-73.95976,United States,US,<NA>,NaN,Entire home/apt,<NA>,693.0,139.0,2,358,2019-06-20,3.44,3,2,286,There is no parking on my street for guests. Y...
204,1114005,NaN,20738355824,NaN,Nicholas,Manhattan,Hell's Kitchen,40.76548,-73.98474,United States,US,<NA>,NaN,Shared room,<NA>,586.0,117.0,6,10,2014-01-07,0.09,1,1,<NA>,NaN
205,1114558,NaN,27207072817,NaN,Jack,Manhattan,Harlem,40.80234,-73.95603,United States,US,<NA>,NaN,Private room,<NA>,112.0,22.0,30,0,NaT,NaN,1,1,12,Shoes off please Cat can go in or out as he de...
351,1195193,NaN,29685226762,unconfirmed,West,Brooklyn,Bedford-Stuyvesant,40.69305,-73.93185,United States,US,<NA>,NaN,Entire home/apt,2014,1056.0,211.0,2,370,2019-07-05,3.74,4,1,<NA>,"No candles, maximum 2 guests"
401,1222808,"Luxe, Spacious 2BR 2BA Nr Trains",27899766790,verified,Alexander,Brooklyn,Gowanus,40.66862,-73.99260,United States,US,<NA>,NaN,Entire home/apt,2010,281.0,56.0,30,3,2014-08-04,0.03,4,1,316,NaN
402,1223361,City Room - Street View Apt,9734975215,unconfirmed,Hawkins,Manhattan,Harlem,40.81333,-73.94453,United States,US,<NA>,NaN,Entire home/apt,2022,280.0,56.0,1,116,2019-06-13,1.18,4,5,289,NaN
403,1223913,Cozy and Bright One Bedroom in BK,21726366543,unconfirmed,Reed,Brooklyn,Greenpoint,40.72473,-73.95199,United States,US,<NA>,NaN,Entire home/apt,2004,NaN,29.0,2,175,2019-07-07,1.79,3,1,119,NaN
404,1224465,Forest Hills Apt minutes to midtown Manhattan,44376825531,unconfirmed,Richards,Queens,Forest Hills,40.70925,-73.85262,United States,US,<NA>,NaN,Entire home/apt,2022,NaN,56.0,3,28,2019-07-01,1.21,5,3,270,"Your our guest, so please make yourself at hom..."
405,1225018,Spacious West Village 1 b/room King,65582846543,verified,Kelly,Manhattan,West Village,40.73215,-74.00922,United States,US,<NA>,NaN,Entire home/apt,2011,NaN,157.0,4,24,2017-12-26,0.25,5,1,<NA>,Guest is expected to behave in a nice and orde...
406,1225570,Perfect Williamsburg Summer Haven,54156502664,unconfirmed,Phillips,Brooklyn,Williamsburg,40.71109,-73.94332,United States,US,<NA>,NaN,Entire home/apt,2006,250.0,50.0,2,15,2016-06-06,0.15,5,1,155,1. No additional guests not part of the reserv...
407,1226122,Midtown cozy convenient,74817474743,unconfirmed,Craig,Manhattan,Murray Hill,40.74630,-73.97926,United States,US,<NA>,NaN,Private room,2004,430.0,86.0,4,105,2019-06-06,1.07,2,1,313,NaN
408,1226674,Prime Williamsburg Apartment,4148477175,unconfirmed,Henderson,Brooklyn,Williamsburg,40.71823,-73.95849,United States,US,<NA>,NaN,Entire home/apt,2017,1170.0,234.0,10,22,2019-05-30,0.38,5,1,287,NaN
409,1227227,"Private, spacious room in Brooklyn",7773611662,unconfirmed,Davis,Brooklyn,East Flatbush,40.65100,-73.94886,United States,US,<NA>,NaN,Private room,2007,572.0,114.0,2,263,2019-06-24,2.69,3,2,<NA>,NaN
410,1227779,Garden apartment close to Manhattan,56605529359,verified,Anderson,Brooklyn,Fort Greene,40.68626,-73.97598,United States,US,<NA>,NaN,Entire home/apt,2014,173.0,35.0,3,86,2019-06-20,0.91,5,2,<NA>,• Check-in time is 4PM. As me and my roommates...
411,1228331,The Ground Studio - West Side,15828748157,verified,Moore,Manhattan,Chelsea,40.74488,-74.00100,United States,US,<NA>,NaN,Entire home/apt,2011,1092.0,218.0,4,10,2017-01-01,0.10,3,1,<NA>,No smoking in the bedroom. Smoking is allowed ...
412,1228884,Stunning arty 3200sf 3FLR+3BR townhome w/terrace,63587153380,unconfirmed,Alissa,Brooklyn,Park Slope,40.67632,-73.97616,United States,US,<NA>,NaN,Entire home/apt,2016,1033.0,207.0,7,18,2019-05-27,0.21,1,1,<NA>,NaN
516,1286323,Comfort at Crossroads of Downtown,82992556236,verified,Kevin,Manhattan,Chelsea,40.73862,-73.99758,United States,US,<NA>,NaN,Entire home/apt,2018,NaN,83.0,1,2,2015-08-28,0.02,2,1,256,"We expect our guests to be honest, to treat ou..."
517,1286875,"""The Oasis"" on Bedford Williamsburg",30603782652,unconfirmed,Lucas,Brooklyn,NaN,40.71580,-73.95803,United States,US,<NA>,NaN,Entire home/apt,2005,NaN,130.0,6,1,2016-01-01,0.02,5,1,266,1. No parties. 2. Respect the neighbors. Nois...
518,1287427,"Large, sunny garden apartment.",74260924259,unconfirmed,Spike,Brooklyn,Prospect Heights,40.68262,-73.97299,United States,US,<NA>,NaN,Entire home/apt,2019,869.0,174.0,3,67,2018-10-20,0.70,1,1,18,1. Guests should be considerate of the other r...
519,1287980,UNION SQUARE/ E. VILL 1BR BEAUTIFUL,65125319788,verified,Tess,Manhattan,East Village,40.73217,-73.98801,United States,US,<NA>,NaN,Entire home/apt,2003,931.0,186.0,1,63,2018-01-12,0.68,1,1,349,NaN
520,1288532,Hell's Kitchen Funky 80's Hideaway!,48327323941,unconfirmed,Sydney,Manhattan,Hell's Kitchen,40.76311,-73.99388,United States,US,<NA>,NaN,Private room,2007,781.0,156.0,1,89,2019-07-01,1.00,1,1,<NA>,Please remember that this is a residential bui...
595,1329955,Quiet sunny studio Midtown,57412920877,verified,Abraham,Manhattan,Midtown,40.74267,-73.98569,United States,US,<NA>,NaN,Entire home/apt,2010,1104.0,221.0,4,3,2018-12-26,0.03,4,1,1,NaN
596,1330507,Charming room in Victorian home,9899986845,unconfirmed,Sienna,Brooklyn,Bedford-Stuyvesant,40.68749,-73.95494,United States,US,<NA>,NaN,Private room,2021,830.0,166.0,3,115,2019-07-05,1.21,5,3,144,Please remember that this is a residential bui...
597,1331059,Brooklyn B & B close to Manhattan,50967627357,verified,David,Brooklyn,Fort Greene,40.68645,-73.97538,United States,US,<NA>,NaN,Private room,2005,608.0,122.0,3,154,2019-06-19,1.63,1,2,<NA>,NaN
598,1331611,The Notorious B.N.B. { The Erhart },32729811162,unconfirmed,Edgar,Brooklyn,Clinton Hill,40.68999,-73.96711,United States,US,<NA>,NaN,Private room,2020,576.0,115.0,1,164,2019-07-01,1.73,4,11,47,Guests must be fit enough to maneuver themselv...
599,1332164,Sunny cozy multileveled apartment!,59272298800,unconfirmed,Audrey,Staten Island,Shore Acres,40.61077,-74.06824,United States,US,<NA>,NaN,Entire home/apt,2003,675.0,135.0,6,76,2019-06-13,0.80,5,1,253,Please remember that this is a residential bui...
600,1332716,Sunny 2 bedroom Williamsburg Duplex w/ 3 beds,57211550677,verified,Julia,Brooklyn,Williamsburg,40.71126,-73.94576,United States,US,<NA>,NaN,Entire home/apt,2012,747.0,149.0,3,116,2019-06-30,1.23,3,2,150,NaN
601,1333268,ROOM WITH KITCHENETTE #2,24025629258,unconfirmed,Vanessa,Brooklyn,Bedford-Stuyvesant,40.67855,-73.94949,United States,US,<NA>,NaN,Entire home/apt,2014,805.0,161.0,3,234,2019-06-30,2.47,1,4,265,NaN
602,1333821,Alpha-Bet City entire floor large cool 2br -L.E.S,76723251474,unconfirmed,Arnold,Manhattan,East Village,40.72416,-73.98530,United States,US,<NA>,NaN,Entire home/apt,<NA>,574.0,115.0,2,120,2019-06-24,1.27,2,1,271,Please remember that this is a residential bui...
603,1334373,"Your Haven Awaits At ""Emma's Place""",45317219946,unconfirmed,Maddie,Brooklyn,Bedford-Stuyvesant,40.68516,-73.92521,United States,US,<NA>,NaN,Entire home/apt,<NA>,52.0,10.0,4,82,2019-05-18,0.87,2,1,248,• Check-in time is 12PM (noon). • Check-in tim...
604,1334925,"Spacious, Kid-Friendly 2 BR in West Village",55328430242,verified,Melissa,Manhattan,West Village,40.73507,-74.00048,United States,US,<NA>,NaN,Entire home/apt,2004,694.0,139.0,3,13,2019-05-26,0.15,1,1,221,NaN
675,1374139,Loft Suite @ Box House Hotel,20579239232,unconfirmed,Gibson,Brooklyn,Greenpoint,40.73730,-73.95323,United States,US,<NA>,NaN,Entire home/apt,2005,534.0,107.0,3,24,2019-04-25,0.26,3,28,26,House Rules Welcome to Boston-Furnished-Rental...
676,1374691,Loft Suite @ The Box House Hotel,53927684523,verified,Richardson,Brooklyn,Greenpoint,40.73708,-73.95271,United States,US,<NA>,NaN,Entire home/apt,2006,947.0,189.0,3,23,2019-06-22,0.26,3,28,<NA>,House Rules Welcome to Boston-Furnished-Rental...
677,1375243,Loft Suite @ The Box House Hotel,17810750507,verified,Spencer,Brooklyn,Greenpoint,40.73652,-73.95236,United States,US,<NA>,NaN,Entire home/apt,2019,847.0,169.0,3,43,2019-07-02,0.47,4,28,<NA>,"Expect to have our place treated with respect,..."
678,1375795,Loft Suite @ The Box House Hotel,34416621424,verified,Smith,Brooklyn,NaN,40.73693,-73.95316,United States,US,<NA>,NaN,Entire home/apt,2018,914.0,183.0,3,30,2019-07-03,0.32,5,28,296,House Rules Welcome to Boston-Furnished-Rental...
679,1376348,Loft Suite @ The Box House Hotel,87064762165,unconfirmed,Stevens,Brooklyn,Greenpoint,40.73784,-73.95324,United States,US,<NA>,NaN,Entire home/apt,2019,757.0,151.0,3,39,2019-06-29,0.44,1,28,77,No Smoking on the apartment. No Ilegal Drugs ...
680,1376900,Duplex w/ Terrace @ Box House Hotel,98324965537,verified,Morris,Brooklyn,Greenpoint,40.73674,-73.95247,United States,US,<NA>,NaN,Private room,2012,719.0,144.0,3,8,2018-07-26,0.09,5,28,16,No Smoking on the apartment. No Ilegal Drugs ...
51034,29187414,Double bedroom with ensuite in spacious NYC loft,6212352335,unconfirmed,Romilly,Manhattan,NoHo,40.72774,-73.99242,United States,US,<NA>,NaN,Private room,2018,277.0,55.0,1,8,2022-02-27,5.71,2,1,4,NaN
51035,29187967,Near Airport LGA Small Room Bright Self Check-in!,39508745682,unconfirmed,Angel,Queens,East Elmhurst,40.76547,-73.87559,United States,US,<NA>,NaN,Private room,2003,1056.0,211.0,1,66,2022-02-27,4.64,4,2,364,NaN
51036,29188519,Cozy Williamsburg waterfront apartment,43343559686,unconfirmed,Douglass,Brooklyn,Williamsburg,40.71821,-73.96456,United States,US,<NA>,NaN,Entire home/apt,2010,373.0,75.0,7,1,2022-02-27,1.00,3,1,309,NaN
51037,29189071,Cozy room with Private bathroom in Ditmas Park,22964340966,unconfirmed,Tyrel,Brooklyn,Flatbush,40.63629,-73.96102,United States,US,<NA>,NaN,Entire home/apt,2015,731.0,146.0,1,34,2022-02-27,2.47,5,1,74,NaN
51038,29189623,Comfy Large Studio,73165100565,unconfirmed,Van,Brooklyn,Bedford-Stuyvesant,40.68524,-73.93153,United States,US,<NA>,NaN,Entire home/apt,2009,845.0,169.0,1,10,2022-02-27,0.68,3,5,162,NaN
51039,29190176,Bright duplex w/ lush roof garden & skyline views,66232862302,verified,Jeroen,Brooklyn,Clinton Hill,40.68838,-73.96725,United States,US,<NA>,NaN,Entire home/apt,2013,141.0,28.0,2,6,2022-02-27,0.44,5,1,36,NaN
51040,29190728,The Paul Hotel Chelsea Luxury that sleeps 4,18449732408,unconfirmed,Vk,Manhattan,Chelsea,40.74720,-73.98996,United States,US,<NA>,NaN,Private room,2021,392.0,78.0,1,24,2022-02-27,1.87,3,26,112,NaN
83525,47132194,COZY QUIET APT CLOSE TO TRAIN,37679078635,unconfirmed,Alana,Brooklyn,Bushwick,40.70073,-73.92913,United States,US,<NA>,NaN,Private room,2012,685.0,137.0,3,4,2017-12-26,0.20,5,1,0,NaN
83526,47132746,Sunny/spacious/convenient private room - Bushw...,33028729041,verified,Rahul,Brooklyn,Bushwick,40.69808,-73.93022,United States,US,<NA>,NaN,Private room,2013,204.0,41.0,2,76,2019-07-06,4.03,5,1,234,NaN
83527,47133298,Creative Artist Apartment in SoBro,42128629166,unconfirmed,Jermaine,Bronx,Mott Haven,40.81553,-73.92453,United States,US,<NA>,NaN,Entire home/apt,2015,513.0,103.0,2,0,NaT,NaN,3,1,0,NaN
83528,47133850,Prime East Village REAL 1 Bedroom,50727450322,verified,David,Manhattan,East Village,40.72236,-73.97756,United States,US,<NA>,NaN,Entire home/apt,2019,1153.0,231.0,5,0,NaT,NaN,3,1,0,NaN
83529,47134403,"Quiet, clean and spacious.",57673612097,verified,Peter,Manhattan,Upper West Side,40.77867,-73.97914,United States,US,<NA>,NaN,Private room,2017,368.0,74.0,7,8,2019-06-16,0.82,3,1,363,NaN
83530,47134955,Vics cafe,66734779569,verified,Victor,Queens,Queens Village,40.72517,-73.76105,United States,US,<NA>,NaN,Shared room,2009,955.0,191.0,1,11,2019-06-03,0.51,3,2,125,I expect you to keep the apartment picked up a...
83531,47135507,The Perfect Fort Greene Studio,58906963506,unconfirmed,Brooke,Brooklyn,Fort Greene,40.68805,-73.97563,United States,US,<NA>,NaN,Entire home/apt,2019,805.0,161.0,2,1,2017-10-01,0.05,4,1,0,1. No house parties 2. Do not damage any of th...
83532,47136060,Sun-filled Bed-Stuy Apt with Master Bedroom!,53258837971,unconfirmed,Claire,Brooklyn,Bedford-Stuyvesant,40.69321,-73.94207,United States,US,<NA>,NaN,Private room,2005,454.0,91.0,3,5,2019-03-23,0.23,5,1,0,Please remember that this is a residential bui...
83533,47136612,Sunny and charming Room in Duplex Apt in BedStuy,97852750240,verified,Salome,Brooklyn,Bedford-Stuyvesant,40.68808,-73.94130,United States,US,<NA>,NaN,Private room,2015,857.0,171.0,2,6,2018-10-08,0.28,3,1,39,NaN
91020,51271682,1BR Spacious Luxury Apartment in Williamsburg BK,39923384327,verified,Michael & Hanako,Brooklyn,Williamsburg,40.71778,-73.95503,United States,US,<NA>,NaN,Entire home/apt,2015,1185.0,237.0,4,7,2018-04-16,0.24,4,1,0,No pets and no smoking (including outside near...
91021,51272234,Room w/ terrace in house w/ backyard Williamsb...,21108777656,unconfirmed,Valentine,Brooklyn,Williamsburg,40.70833,-73.93916,United States,US,<NA>,NaN,Private room,2015,1139.0,228.0,12,9,2019-05-27,0.37,5,1,11,- I've lived here over 14 years. Love it! B...
91022,51272787,Wonderful Apartment Upper West Side Midtown,72441004046,unconfirmed,Jonathan,Manhattan,Upper West Side,40.77016,-73.98126,United States,US,<NA>,NaN,Entire home/apt,2022,78.0,16.0,7,0,NaT,NaN,3,1,0,-Leave the apartment as you found it. -Quiet ...
91023,51273339,Amazing One Bedroom Apt,63569806723,unconfirmed,Jeffrey,Brooklyn,Bedford-Stuyvesant,40.68080,-73.93753,United States,US,<NA>,NaN,Entire home/apt,2019,467.0,93.0,30,9,2019-04-27,0.34,1,3,319,NaN
91024,51273891,The Gramercy East,82992882228,unconfirmed,Ritchy,Manhattan,Gramercy,40.73575,-73.98000,United States,US,<NA>,NaN,Entire home/apt,2019,1031.0,206.0,2,3,2018-09-29,0.12,4,1,3,We are seeking responsible and respectful gues...
99096,55732057,"Clean, Cozy & Charming Shared Room in Manhattan",3729643509,unconfirmed,Gem,Manhattan,Midtown,40.75729,-73.96807,United States,US,<NA>,NaN,Shared room,2022,502.0,100.0,1,18,2019-06-14,1.97,3,1,52,NaN
99097,55732609,Awesome 1BR in 2 room located in heart of Bush...,30332881457,unconfirmed,JayJay,Brooklyn,Bushwick,40.69582,-73.90950,United States,US,<NA>,NaN,Private room,2006,958.0,192.0,1,0,NaT,NaN,4,1,364,We have put a lot of time and effort into givi...
99098,55733161,Cozy Room in Brooklyn- Sunset Park,37535907002,unconfirmed,Josie,Brooklyn,Sunset Park,40.64634,-74.01419,United States,US,<NA>,NaN,Private room,2011,234.0,47.0,2,8,2019-02-08,0.86,4,2,0,-Remove shoes -be sure to lock the front door ...
99099,55733714,"2-BR Apt 25min from TIMES SQUARE, Near Shops!",40764016645,verified,Vance,Queens,Astoria,40.75975,-73.91992,United States,US,<NA>,NaN,Entire home/apt,2020,324.0,65.0,2,4,2019-06-03,0.46,2,1,20,"The usual ""social code"": There are three of us..."
99100,55734266,Alcove Studio 10 mins walk to Times Square,89054445744,unconfirmed,Nidhi,Manhattan,Hell's Kitchen,40.76591,-73.99493,United States,US,<NA>,NaN,Entire home/apt,2006,264.0,53.0,4,4,2019-05-11,0.44,5,1,5,"Not really a 'rules based' household, or perha..."

In [69]:
df[df["service_fee"].isna()][
    ["price", "service_fee", "room_type", "neighbourhood_group", "neighbourhood"]
]

,price,service_fee,room_type,neighbourhood_group,neighbourhood
15,578.0,NaN,Entire home/apt,Manhattan,West Village
16,778.0,NaN,Entire home/apt,Brooklyn,Williamsburg
17,656.0,NaN,Entire home/apt,Brooklyn,Fort Greene
18,460.0,NaN,Private room,Manhattan,Chelsea
19,1095.0,NaN,Entire home/apt,Brooklyn,Crown Heights
2168,1093.0,NaN,Private room,Brooklyn,Bushwick
2169,90.0,NaN,Shared room,Manhattan,East Harlem
2170,1051.0,NaN,Entire home/apt,Manhattan,Upper East Side
2171,891.0,NaN,Private room,Manhattan,Upper West Side
2172,802.0,NaN,Entire home/apt,Brooklyn,South Slope
2173,1129.0,NaN,Shared room,Manhattan,Harlem
2174,256.0,NaN,Private room,Manhattan,Harlem
2175,1044.0,NaN,Entire home/apt,Brooklyn,Carroll Gardens
2176,917.0,NaN,Entire home/apt,Brooklyn,Williamsburg
2177,649.0,NaN,Entire home/apt,Queens,Astoria
6614,357.0,NaN,Entire home/apt,Manhattan,East Village
6615,651.0,NaN,Private room,Brooklyn,Williamsburg
6616,252.0,NaN,Private room,Queens,Woodhaven
6617,386.0,NaN,Private room,Queens,Rego Park
6618,111.0,NaN,Entire home/apt,Manhattan,Upper West Side
6619,135.0,NaN,Entire home/apt,Manhattan,Chelsea
6620,238.0,NaN,Entire home/apt,Manhattan,Midtown
6621,499.0,NaN,Entire home/apt,Manhattan,Tribeca
6647,1194.0,NaN,Entire home/apt,Manhattan,Upper West Side
6648,889.0,NaN,Private room,Brooklyn,Prospect-Lefferts Gardens
6649,1029.0,NaN,Entire home/apt,Manhattan,Gramercy
6650,1044.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
6651,1165.0,NaN,Private room,Brooklyn,Williamsburg
6652,1119.0,NaN,Private room,Brooklyn,Williamsburg
6653,1161.0,NaN,Entire home/apt,Queens,Astoria
6654,950.0,NaN,Entire home/apt,Manhattan,Harlem
13422,92.0,NaN,Entire home/apt,Manhattan,Little Italy
13423,1099.0,NaN,Entire home/apt,Manhattan,Chelsea
13424,1040.0,NaN,Entire home/apt,Manhattan,West Village
13425,750.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
13426,805.0,NaN,Entire home/apt,Manhattan,NoHo
13427,515.0,NaN,Entire home/apt,Manhattan,Nolita
13428,72.0,NaN,Private room,Manhattan,Upper West Side
13429,1196.0,NaN,Entire home/apt,Brooklyn,Greenpoint
13430,240.0,NaN,Entire home/apt,Manhattan,Nolita
13431,451.0,NaN,Entire home/apt,Brooklyn,Crown Heights
13432,699.0,NaN,Private room,Brooklyn,Williamsburg
13433,382.0,NaN,Entire home/apt,Brooklyn,Park Slope
13434,1110.0,NaN,Entire home/apt,Brooklyn,Boerum Hill
13435,918.0,NaN,Entire home/apt,Brooklyn,Flatbush
13436,685.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
13446,803.0,NaN,Entire home/apt,Manhattan,Upper East Side
13447,521.0,NaN,Entire home/apt,Brooklyn,Crown Heights
13448,529.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
13449,258.0,NaN,Entire home/apt,Manhattan,Harlem
13450,901.0,NaN,Private room,Manhattan,West Village
13451,129.0,NaN,Entire home/apt,Manhattan,SoHo
13452,1109.0,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
13453,990.0,NaN,Entire home/apt,Manhattan,Upper West Side
13454,563.0,NaN,Entire home/apt,Queens,Jamaica
13595,NaN,NaN,Private room,Brooklyn,Park Slope
13596,NaN,NaN,Entire home/apt,Manhattan,East Harlem
13597,NaN,NaN,Entire home/apt,Brooklyn,Williamsburg
13598,NaN,NaN,Private room,Brooklyn,Williamsburg
13599,NaN,NaN,Private room,Manhattan,East Village
13600,NaN,NaN,Private room,Manhattan,Harlem
13601,NaN,NaN,Entire home/apt,Bronx,Bronxdale
29039,990.0,NaN,Entire home/apt,Manhattan,Hell's Kitchen
29040,1048.0,NaN,Shared room,Brooklyn,Clinton Hill
29041,116.0,NaN,Private room,Brooklyn,Bushwick
29042,785.0,NaN,Private room,Manhattan,Harlem
29043,634.0,NaN,Entire home/apt,Brooklyn,Bushwick
29044,642.0,NaN,Private room,Manhattan,East Village
29045,90.0,NaN,Private room,Brooklyn,Williamsburg
29046,1006.0,NaN,Private room,Brooklyn,Bushwick
29047,856.0,NaN,Private room,Brooklyn,Bushwick
29048,920.0,NaN,Entire home/apt,Brooklyn,East Flatbush
29049,838.0,NaN,Private room,Manhattan,East Village
29050,1090.0,NaN,Private room,Brooklyn,Bushwick
29051,516.0,NaN,Private room,Manhattan,Upper East Side
29052,995.0,NaN,Entire home/apt,Manhattan,Upper East Side
30896,1096.0,NaN,Private room,Queens,Flushing
30897,379.0,NaN,Entire home/apt,Brooklyn,Williamsburg
30898,937.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
30899,1134.0,NaN,Private room,Brooklyn,Bushwick
30900,470.0,NaN,Private room,Brooklyn,Greenpoint
30901,835.0,NaN,Private room,Brooklyn,East Flatbush
30902,1133.0,NaN,Entire home/apt,Manhattan,Inwood
30903,699.0,NaN,Private room,Brooklyn,Greenpoint
30904,577.0,NaN,Private room,Manhattan,Hell's Kitchen
30905,297.0,NaN,Private room,Brooklyn,Flatbush
37134,457.0,NaN,Private room,Manhattan,Harlem
37135,601.0,NaN,Entire home/apt,Brooklyn,Crown Heights
37136,265.0,NaN,Private room,Brooklyn,Flatbush
37137,869.0,NaN,Entire home/apt,Manhattan,Lower East Side
37138,867.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
37139,274.0,NaN,Private room,Staten Island,West Brighton
37140,136.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
37141,614.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
37169,NaN,NaN,Private room,Brooklyn,Bushwick
37170,NaN,NaN,Private room,Brooklyn,Bushwick
37171,NaN,NaN,Private room,Brooklyn,Bushwick
37172,NaN,NaN,Private room,Brooklyn,Bushwick
37173,NaN,NaN,Private room,Brooklyn,Bushwick
37174,NaN,NaN,Entire home/apt,Manhattan,Upper East Side
37175,NaN,NaN,Entire home/apt,Manhattan,East Harlem
37176,NaN,NaN,Shared room,Brooklyn,Bedford-Stuyvesant
37263,NaN,NaN,Entire home/apt,Brooklyn,Cypress Hills
37264,NaN,NaN,Private room,Brooklyn,Bedford-Stuyvesant
37265,NaN,NaN,Private room,Brooklyn,Bedford-Stuyvesant
37266,NaN,NaN,Entire home/apt,Manhattan,East Village
37267,NaN,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
37268,NaN,NaN,Private room,Manhattan,Upper West Side
37269,NaN,NaN,Private room,Manhattan,Hell's Kitchen
37270,NaN,NaN,Entire home/apt,Manhattan,SoHo
38465,774.0,NaN,Private room,Brooklyn,Bushwick
38466,890.0,NaN,Private room,Brooklyn,East Flatbush
38467,611.0,NaN,Entire home/apt,Manhattan,Chelsea
38468,696.0,NaN,Entire home/apt,Manhattan,East Harlem
38469,1030.0,NaN,Private room,Brooklyn,Sheepshead Bay
38470,937.0,NaN,Private room,Brooklyn,Bay Ridge
38471,620.0,NaN,Entire home/apt,Manhattan,Washington Heights
38472,633.0,NaN,Private room,Manhattan,Inwood
38473,616.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
38474,1079.0,NaN,Entire home/apt,Brooklyn,East Flatbush
38475,870.0,NaN,Entire home/apt,Brooklyn,Carroll Gardens
38476,297.0,NaN,Private room,Manhattan,Hell's Kitchen
41175,419.0,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
41176,967.0,NaN,Entire home/apt,Manhattan,East Harlem
41177,344.0,NaN,Private room,Queens,Sunnyside
41178,74.0,NaN,Private room,Manhattan,Washington Heights
41179,1066.0,NaN,Private room,Manhattan,Lower East Side
41180,494.0,NaN,Private room,Manhattan,Harlem
41181,752.0,NaN,Entire home/apt,Brooklyn,Fort Greene
51221,230.0,NaN,Entire home/apt,Manhattan,West Village
51222,1148.0,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
51223,802.0,NaN,Entire home/apt,Queens,Woodside
51224,665.0,NaN,Private room,Manhattan,Harlem
51225,865.0,NaN,Entire home/apt,Manhattan,East Village
51226,156.0,NaN,Entire home/apt,Manhattan,Midtown
51227,337.0,NaN,Private room,Manhattan,Midtown
51228,328.0,NaN,Private room,Manhattan,Chelsea
51229,1078.0,NaN,Private room,Queens,Ridgewood
51230,571.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
51231,827.0,NaN,Private room,Brooklyn,Bushwick
65592,659.0,NaN,Private room,Brooklyn,Crown Heights
65593,519.0,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
65594,604.0,NaN,Private room,Queens,Edgemere
65595,917.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
65596,502.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
65683,1037.0,NaN,Private room,Brooklyn,Flatbush
65684,1175.0,NaN,Private room,Brooklyn,Crown Heights
65685,311.0,NaN,Entire home/apt,Manhattan,Kips Bay
65686,553.0,NaN,Private room,Queens,Long Island City
65687,726.0,NaN,Entire home/apt,Brooklyn,Bath Beach
65688,231.0,NaN,Entire home/apt,Manhattan,Nolita
65689,788.0,NaN,Entire home/apt,Manhattan,Hell's Kitchen
65690,1168.0,NaN,Private room,Bronx,Wakefield
65691,299.0,NaN,Private room,Queens,Woodside
65692,897.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
65693,1107.0,NaN,Entire home/apt,Queens,Ozone Park
65694,133.0,NaN,Entire home/apt,Manhattan,Hell's Kitchen
65695,223.0,NaN,Private room,Manhattan,Financial District
65696,117.0,NaN,Private room,Queens,Ridgewood
65697,373.0,NaN,Private room,Queens,Maspeth
65698,1167.0,NaN,Entire home/apt,Staten Island,West Brighton
65699,718.0,NaN,Entire home/apt,Manhattan,Midtown
65700,225.0,NaN,Entire home/apt,Manhattan,Marble Hill
65810,795.0,NaN,Entire home/apt,Manhattan,Midtown
65811,525.0,NaN,Entire home/apt,Manhattan,Two Bridges
65812,129.0,NaN,Entire home/apt,Brooklyn,Prospect-Lefferts Gardens
65813,1165.0,NaN,Entire home/apt,Manhattan,Washington Heights
65814,146.0,NaN,Private room,Bronx,Hunts Point
65815,767.0,NaN,Private room,Manhattan,East Village
65816,1054.0,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
65817,881.0,NaN,Entire home/apt,Queens,Long Island City
65818,1138.0,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
65819,634.0,NaN,Entire home/apt,Brooklyn,Bushwick
65820,449.0,NaN,Private room,Manhattan,Harlem
65821,923.0,NaN,Private room,Queens,Woodside
65822,336.0,NaN,Private room,Brooklyn,Prospect Heights
65823,342.0,NaN,Entire home/apt,Brooklyn,Greenpoint
65824,522.0,NaN,Private room,Brooklyn,Williamsburg
65825,1116.0,NaN,Entire home/apt,Brooklyn,Greenpoint
65891,302.0,NaN,Entire home/apt,Queens,Ridgewood
65892,179.0,NaN,Entire home/apt,Brooklyn,East Flatbush
65893,1099.0,NaN,Entire home/apt,Manhattan,Upper East Side
65894,318.0,NaN,Entire home/apt,Queens,Jamaica
65895,1102.0,NaN,Private room,Bronx,Belmont
65896,985.0,NaN,Private room,Queens,Flushing
65897,50.0,NaN,Private room,Manhattan,Midtown
65898,916.0,NaN,Hotel room,Manhattan,SoHo
65899,84.0,NaN,Private room,Queens,Flushing
65900,908.0,NaN,Private room,Manhattan,Midtown
65901,1110.0,NaN,Entire home/apt,Manhattan,Tribeca
65987,470.0,NaN,Private room,Manhattan,East Harlem
65988,982.0,NaN,Private room,Queens,Astoria
65989,413.0,NaN,Entire home/apt,Brooklyn,Greenpoint
65990,731.0,NaN,Entire home/apt,Brooklyn,East New York
65991,637.0,NaN,Private room,Queens,Astoria
65992,223.0,NaN,Private room,Queens,Sunnyside
65993,1024.0,NaN,Private room,Brooklyn,Bushwick
65994,800.0,NaN,Entire home/apt,Manhattan,East Harlem
65995,839.0,NaN,Private room,Brooklyn,Crown Heights
65996,823.0,NaN,Private room,Manhattan,Financial District
65997,961.0,NaN,Entire home/apt,Manhattan,Battery Park City
65998,1125.0,NaN,Entire home/apt,Brooklyn,Williamsburg
65999,733.0,NaN,Private room,Brooklyn,Williamsburg
66000,693.0,NaN,Entire home/apt,Brooklyn,Williamsburg
66001,720.0,NaN,Private room,Manhattan,SoHo
66002,980.0,NaN,Hotel room,Manhattan,Midtown
66003,628.0,NaN,Private room,Manhattan,Harlem
66004,819.0,NaN,Private room,Brooklyn,Carroll Gardens
66063,1137.0,NaN,Private room,Queens,Elmhurst
66064,434.0,NaN,Private room,Brooklyn,Gravesend
66065,1150.0,NaN,Private room,Queens,Woodside
66066,707.0,NaN,Entire home/apt,Manhattan,East Village
66067,914.0,NaN,Private room,Queens,Woodside
66068,682.0,NaN,Entire home/apt,Manhattan,Morningside Heights
66069,373.0,NaN,Entire home/apt,Queens,Glendale
66070,325.0,NaN,Entire home/apt,Brooklyn,Borough Park
66071,1187.0,NaN,Entire home/apt,Queens,Flushing
66072,502.0,NaN,Private room,Manhattan,Murray Hill
66073,1139.0,NaN,Private room,Queens,Rego Park
66074,284.0,NaN,Entire home/apt,Brooklyn,Williamsburg
66075,293.0,NaN,Entire home/apt,Manhattan,Chelsea
66076,144.0,NaN,Private room,Manhattan,Kips Bay
67821,299.0,NaN,Entire home/apt,Manhattan,Hell's Kitchen
67822,994.0,NaN,Private room,Brooklyn,Boerum Hill
67823,1147.0,NaN,Entire home/apt,Brooklyn,Sunset Park
67824,755.0,NaN,Entire home/apt,Manhattan,Upper East Side
67825,659.0,NaN,Entire home/apt,Brooklyn,Williamsburg
67826,429.0,NaN,Private room,Bronx,Pelham Gardens
67827,769.0,NaN,Private room,Manhattan,Upper East Side
67828,1088.0,NaN,Private room,Brooklyn,Crown Heights
79779,344.0,NaN,Entire home/apt,Manhattan,Chelsea
79780,846.0,NaN,Entire home/apt,Manhattan,Harlem
79781,255.0,NaN,Entire home/apt,Manhattan,Morningside Heights
79782,64.0,NaN,Private room,Manhattan,Marble Hill
79783,138.0,NaN,Private room,Manhattan,East Village
79784,928.0,NaN,Entire home/apt,Brooklyn,Clinton Hill
79785,NaN,NaN,Private room,Queens,Flushing
79786,NaN,NaN,Private room,Brooklyn,East Flatbush
79787,NaN,NaN,Entire home/apt,Manhattan,Harlem
79788,NaN,NaN,Private room,Manhattan,Midtown
79789,NaN,NaN,Private room,Staten Island,Stapleton
97704,118.0,NaN,Entire home/apt,Brooklyn,Bay Ridge
97705,378.0,NaN,Private room,Brooklyn,Bushwick
97706,276.0,NaN,Private room,Manhattan,Washington Heights
97707,350.0,NaN,Entire home/apt,Brooklyn,Prospect-Lefferts Gardens
97708,630.0,NaN,Entire home/apt,Manhattan,Kips Bay
97760,523.0,NaN,Entire home/apt,Brooklyn,Sunset Park
97761,104.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
97762,1033.0,NaN,Entire home/apt,Manhattan,Harlem
97763,151.0,NaN,Entire home/apt,Queens,Douglaston
97764,1077.0,NaN,Entire home/apt,Brooklyn,Windsor Terrace
97765,326.0,NaN,Private room,Manhattan,Upper West Side
97766,1005.0,NaN,Entire home/apt,Manhattan,East Harlem
102033,303.0,NaN,Private room,Queens,Long Island City
102034,764.0,NaN,Private room,Queens,Long Island City
102035,138.0,NaN,Private room,Brooklyn,Williamsburg
102036,1073.0,NaN,Private room,Brooklyn,Bedford-Stuyvesant
102037,531.0,NaN,Private room,Bronx,Olinville
102038,570.0,NaN,Private room,Brooklyn,Williamsburg
102039,665.0,NaN,Entire home/apt,Manhattan,Inwood
102045,NaN,NaN,Private room,Queens,Rego Park
102046,NaN,NaN,Private room,Brooklyn,Bushwick
102047,NaN,NaN,Private room,Brooklyn,Williamsburg
102048,NaN,NaN,Entire home/apt,Manhattan,Upper West Side
102049,NaN,NaN,Entire home/apt,Manhattan,Hell's Kitchen
102050,NaN,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
102051,147.0,NaN,Private room,Brooklyn,East New York
102052,1183.0,NaN,Private room,Manhattan,Inwood
102053,696.0,NaN,Private room,Brooklyn,Flatbush
102054,909.0,NaN,Private room,Brooklyn,Bushwick
102055,387.0,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
102056,848.0,NaN,Private room,Manhattan,Harlem
102057,1128.0,NaN,Entire home/apt,Manhattan,Harlem

In [70]:
df[df["price"].isna()][
    ["price", "service_fee", "room_type", "neighbourhood_group", "neighbourhood"]
]

,price,service_fee,room_type,neighbourhood_group,neighbourhood
147,NaN,64.0,Entire home/apt,Brooklyn,Williamsburg
148,NaN,119.0,Entire home/apt,Manhattan,East Village
210,NaN,176.0,Entire home/apt,Brooklyn,Williamsburg
211,NaN,152.0,Private room,Brooklyn,Bedford-Stuyvesant
212,NaN,151.0,Private room,Manhattan,NoHo
213,NaN,48.0,Entire home/apt,Manhattan,West Village
403,NaN,29.0,Entire home/apt,Brooklyn,Greenpoint
404,NaN,56.0,Entire home/apt,Queens,Forest Hills
405,NaN,157.0,Entire home/apt,Manhattan,West Village
516,NaN,83.0,Entire home/apt,Manhattan,Chelsea
517,NaN,130.0,Entire home/apt,Brooklyn,NaN
5882,NaN,27.0,Entire home/apt,Manhattan,East Village
5883,NaN,118.0,Entire home/apt,Manhattan,Greenwich Village
5884,NaN,218.0,Entire home/apt,Brooklyn,Sunset Park
5885,NaN,144.0,Entire home/apt,Manhattan,Upper East Side
5886,NaN,71.0,Entire home/apt,Manhattan,East Village
5908,NaN,68.0,Private room,Brooklyn,Williamsburg
5909,NaN,83.0,Entire home/apt,Manhattan,Upper East Side
5910,NaN,43.0,Private room,Manhattan,East Village
5911,NaN,93.0,Private room,Manhattan,East Village
5979,NaN,50.0,Entire home/apt,Manhattan,East Harlem
5980,NaN,100.0,Entire home/apt,Manhattan,East Village
5981,NaN,190.0,Private room,Brooklyn,Bushwick
5982,NaN,152.0,Entire home/apt,Brooklyn,Bedford-Stuyvesant
5983,NaN,66.0,Entire home/apt,Manhattan,East Village
6054,NaN,112.0,Entire home/apt,Queens,Jamaica Estates
6055,NaN,149.0,Entire home/apt,Manhattan,East Village
6056,NaN,187.0,Shared room,Manhattan,Chelsea
6057,NaN,87.0,Entire home/apt,Manhattan,Harlem
13460,NaN,195.0,Private room,Brooklyn,Flatbush
13461,NaN,142.0,Private room,Brooklyn,Bedford-Stuyvesant
13462,NaN,82.0,Entire home/apt,Brooklyn,Williamsburg
13463,NaN,10.0,Entire home/apt,Manhattan,Morningside Heights
13464,NaN,78.0,Private room,Brooklyn,Williamsburg
13465,NaN,206.0,Entire home/apt,Brooklyn,Williamsburg
13466,NaN,115.0,Private room,Manhattan,Kips Bay
13467,NaN,209.0,Entire home/apt,Brooklyn,Greenpoint
13501,NaN,177.0,Shared room,Brooklyn,Crown Heights
13502,NaN,36.0,Private room,Brooklyn,Greenpoint
13503,NaN,123.0,Entire home/apt,Brooklyn,Bushwick
13504,NaN,28.0,Private room,Manhattan,East Village
13505,NaN,205.0,Private room,Brooklyn,Crown Heights
13506,NaN,172.0,Private room,Brooklyn,Bushwick
13507,NaN,55.0,Entire home/apt,Manhattan,Greenwich Village
13508,NaN,162.0,Private room,Manhattan,Hell's Kitchen
13509,NaN,212.0,Entire home/apt,Manhattan,Upper West Side
13510,NaN,100.0,Entire home/apt,Brooklyn,Crown Heights
13511,NaN,171.0,Private room,Brooklyn,Bedford-Stuyvesant
13512,NaN,113.0,Entire home/apt,Manhattan,SoHo
13547,NaN,67.0,Entire home/apt,Manhattan,Upper East Side
13548,NaN,111.0,Shared room,Manhattan,Lower East Side
13549,NaN,232.0,Private room,Manhattan,Chinatown
13550,NaN,172.0,Private room,Manhattan,Gramercy
13551,NaN,18.0,Private room,Manhattan,Harlem
13552,NaN,204.0,Shared room,Manhattan,East Village
13595,NaN,NaN,Private room,Brooklyn,Park Slope
13596,NaN,NaN,Entire home/apt,Manhattan,East Harlem
13597,NaN,NaN,Entire home/apt,Brooklyn,Williamsburg
13598,NaN,NaN,Private room,Brooklyn,Williamsburg
13599,NaN,NaN,Private room,Manhattan,East Village
13600,NaN,NaN,Private room,Manhattan,Harlem
13601,NaN,NaN,Entire home/apt,Bronx,Bronxdale
18084,NaN,118.0,Private room,Brooklyn,Bedford-Stuyvesant
18085,NaN,73.0,Entire home/apt,Brooklyn,Gowanus
24258,NaN,36.0,Shared room,Brooklyn,Midwood
24259,NaN,113.0,Entire home/apt,Queens,Woodside
24260,NaN,195.0,Entire home/apt,Brooklyn,Williamsburg
24261,NaN,143.0,Private room,Manhattan,Lower East Side
24262,NaN,105.0,Entire home/apt,Manhattan,Midtown
24263,NaN,184.0,Entire home/apt,Manhattan,Chinatown
24264,NaN,142.0,Entire home/apt,Manhattan,Lower East Side
24265,NaN,109.0,Private room,Brooklyn,Crown Heights
24266,NaN,165.0,Entire home/apt,Manhattan,Upper East Side
24326,NaN,82.0,Entire home/apt,Queens,Flushing
24327,NaN,72.0,Private room,Bronx,Fordham
24328,NaN,36.0,Private room,Queens,Astoria
24329,NaN,77.0,Entire home/apt,Brooklyn,Williamsburg
24330,NaN,144.0,Private room,Manhattan,Little Italy
24331,NaN,182.0,Entire home/apt,Queens,Flushing
24332,NaN,84.0,Entire home/apt,Queens,Flushing
24375,NaN,218.0,Private room,Manhattan,Upper West Side
24376,NaN,54.0,Private room,Brooklyn,Sunset Park
24377,NaN,38.0,Entire home/apt,Brooklyn,Crown Heights
24378,NaN,185.0,Entire home/apt,Queens,Jamaica
24379,NaN,226.0,Entire home/apt,Manhattan,Upper East Side
24380,NaN,75.0,Entire home/apt,Brooklyn,Bushwick
24381,NaN,91.0,Entire home/apt,Queens,Flushing
24382,NaN,217.0,Private room,Brooklyn,Greenpoint
24383,NaN,88.0,Private room,Manhattan,Hell's Kitchen
24430,NaN,81.0,Private room,Brooklyn,Crown Heights
24431,NaN,142.0,Private room,Brooklyn,Williamsburg
24432,NaN,44.0,Private room,Queens,Briarwood
24433,NaN,199.0,Private room,Brooklyn,Bushwick
24434,NaN,133.0,Private room,Manhattan,Washington Heights
24435,NaN,128.0,Entire home/apt,Brooklyn,Carroll Gardens
30933,NaN,113.0,Private room,Manhattan,East Village
30934,NaN,41.0,Entire home/apt,Brooklyn,Canarsie
30935,NaN,121.0,Private room,Manhattan,Upper East Side
36794,NaN,159.0,Private room,Queens,Woodhaven
36795,NaN,66.0,Entire home/apt,Brooklyn,Greenpoint
36796,NaN,190.0,Entire home/apt,Manhattan,Upper East Side
36797,NaN,41.0,Entire home/apt,Brooklyn,Bedford-Stuyvesant
36853,NaN,99.0,Entire home/apt,Manhattan,Upper East Side
36854,NaN,61.0,Entire home/apt,Manhattan,Upper West Side
36855,NaN,150.0,Private room,Manhattan,Midtown
36919,NaN,88.0,Entire home/apt,Queens,East Elmhurst
36920,NaN,97.0,Private room,Bronx,Clason Point
36921,NaN,17.0,Private room,Bronx,Unionport
37037,NaN,97.0,Private room,Manhattan,Midtown
37038,NaN,184.0,Entire home/apt,Manhattan,Lower East Side
37039,NaN,13.0,Private room,Manhattan,East Harlem
37040,NaN,179.0,Entire home/apt,Manhattan,East Village
37041,NaN,164.0,Entire home/apt,Brooklyn,Crown Heights
37042,NaN,200.0,Entire home/apt,Manhattan,Upper East Side
37043,NaN,175.0,Entire home/apt,Queens,Astoria
37169,NaN,NaN,Private room,Brooklyn,Bushwick
37170,NaN,NaN,Private room,Brooklyn,Bushwick
37171,NaN,NaN,Private room,Brooklyn,Bushwick
37172,NaN,NaN,Private room,Brooklyn,Bushwick
37173,NaN,NaN,Private room,Brooklyn,Bushwick
37174,NaN,NaN,Entire home/apt,Manhattan,Upper East Side
37175,NaN,NaN,Entire home/apt,Manhattan,East Harlem
37176,NaN,NaN,Shared room,Brooklyn,Bedford-Stuyvesant
37263,NaN,NaN,Entire home/apt,Brooklyn,Cypress Hills
37264,NaN,NaN,Private room,Brooklyn,Bedford-Stuyvesant
37265,NaN,NaN,Private room,Brooklyn,Bedford-Stuyvesant
37266,NaN,NaN,Entire home/apt,Manhattan,East Village
37267,NaN,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant
37268,NaN,NaN,Private room,Manhattan,Upper West Side
37269,NaN,NaN,Private room,Manhattan,Hell's Kitchen
37270,NaN,NaN,Entire home/apt,Manhattan,SoHo
41155,NaN,152.0,Entire home/apt,Manhattan,Murray Hill
41156,NaN,153.0,Private room,Queens,Jackson Heights
41157,NaN,105.0,Private room,Manhattan,Inwood
41158,NaN,118.0,Private room,Brooklyn,East New York
41159,NaN,21.0,Private room,Manhattan,Harlem
41160,NaN,32.0,Entire home/apt,Brooklyn,Bushwick
51214,NaN,38.0,Entire home/apt,Bronx,Tremont
51215,NaN,65.0,Private room,Queens,Ditmars Steinway
51216,NaN,105.0,Entire home/apt,Manhattan,East Village
65609,NaN,200.0,Entire home/apt,Brooklyn,Greenpoint
65610,NaN,63.0,Entire home/apt,Manhattan,Midtown
65611,NaN,157.0,Entire home/apt,Manhattan,Midtown
65612,NaN,23.0,Entire home/apt,Brooklyn,East New York
65613,NaN,143.0,Entire home/apt,Manhattan,Greenwich Village
65641,NaN,239.0,Private room,Brooklyn,Bedford-Stuyvesant
65642,NaN,89.0,Entire home/apt,Manhattan,Chelsea
65643,NaN,12.0,Private room,Brooklyn,Cypress Hills
65644,NaN,71.0,Private room,Brooklyn,Williamsburg
65645,NaN,118.0,Entire home/apt,Manhattan,Lower East Side
65646,NaN,28.0,Entire home/apt,Manhattan,Greenwich Village
65647,NaN,96.0,Private room,Brooklyn,Crown Heights
65648,NaN,91.0,Private room,Bronx,Allerton
65763,NaN,176.0,Entire home/apt,Brooklyn,Flatlands
65764,NaN,197.0,Private room,Brooklyn,Bushwick
65765,NaN,144.0,Entire home/apt,Manhattan,Midtown
65766,NaN,63.0,Entire home/apt,Brooklyn,Williamsburg
65767,NaN,192.0,Entire home/apt,Bronx,Kingsbridge
65768,NaN,171.0,Entire home/apt,Queens,Briarwood
65769,NaN,15.0,Private room,Manhattan,Harlem
65770,NaN,151.0,Private room,Queens,Laurelton
65771,NaN,73.0,Private room,Queens,Sunnyside
65772,NaN,183.0,Private room,Queens,Jackson Heights
65773,NaN,13.0,Entire home/apt,Brooklyn,Bushwick
65852,NaN,165.0,Entire home/apt,Manhattan,Murray Hill
65853,NaN,26.0,Entire home/apt,Manhattan,East Harlem
65854,NaN,87.0,Private room,Manhattan,Financial District
65855,NaN,22.0,Entire home/apt,Brooklyn,Crown Heights
65856,NaN,217.0,Entire home/apt,Manhattan,Chelsea
65857,NaN,174.0,Private room,Queens,Astoria
65858,NaN,226.0,Entire home/apt,Manhattan,Nolita
65859,NaN,105.0,Private room,Manhattan,Midtown
65860,NaN,28.0,Entire home/apt,Manhattan,West Village
65861,NaN,30.0,Entire home/apt,Brooklyn,South Slope
65950,NaN,177.0,Entire home/apt,Staten Island,Arrochar
65951,NaN,66.0,Entire home/apt,Brooklyn,Sunset Park
65952,NaN,142.0,Entire home/apt,Manhattan,Harlem
65953,NaN,22.0,Entire home/apt,Manhattan,Inwood
65954,NaN,237.0,Private room,Queens,Jackson Heights
65955,NaN,118.0,Entire home/apt,Manhattan,Murray Hill
65956,NaN,140.0,Private room,Manhattan,SoHo
65957,NaN,233.0,Private room,Queens,Ridgewood
65958,NaN,209.0,Private room,Queens,Astoria
65959,NaN,68.0,Entire home/apt,Manhattan,Murray Hill
65960,NaN,234.0,Entire home/apt,Manhattan,Midtown
65961,NaN,198.0,Private room,Manhattan,Lower East Side
65962,NaN,183.0,Private room,Queens,Woodside
65963,NaN,112.0,Private room,Brooklyn,Clinton Hill
65964,NaN,90.0,Entire home/apt,Manhattan,Upper West Side
66028,NaN,105.0,Private room,Brooklyn,Bedford-Stuyvesant
66029,NaN,189.0,Private room,Queens,East Elmhurst
66030,NaN,139.0,Entire home/apt,Manhattan,East Village
66031,NaN,15.0,Private room,Manhattan,Financial District
66032,NaN,185.0,Entire home/apt,Brooklyn,Windsor Terrace
66033,NaN,25.0,Private room,Brooklyn,Bedford-Stuyvesant
66034,NaN,152.0,Entire home/apt,Brooklyn,Fort Greene
66035,NaN,226.0,Entire home/apt,Manhattan,East Village
66036,NaN,88.0,Entire home/apt,Brooklyn,Bushwick
66037,NaN,129.0,Entire home/apt,Brooklyn,Prospect-Lefferts Gardens
66038,NaN,204.0,Private room,Queens,Woodside
66107,NaN,71.0,Private room,Manhattan,Harlem
66108,NaN,94.0,Entire home/apt,Queens,Astoria
66109,NaN,148.0,Private room,Manhattan,Harlem
66110,NaN,176.0,Private room,Brooklyn,Williamsburg
66111,NaN,108.0,Private room,Brooklyn,Crown Heights
66112,NaN,108.0,Entire home/apt,Manhattan,East Village
66113,NaN,239.0,Private room,Queens,Ridgewood
66114,NaN,121.0,Private room,Queens,Woodside
66115,NaN,170.0,Entire home/apt,Brooklyn,Clinton Hill
66116,NaN,111.0,Entire home/apt,Manhattan,Chelsea
66117,NaN,229.0,Entire home/apt,Manhattan,East Harlem
79785,NaN,NaN,Private room,Queens,Flushing
79786,NaN,NaN,Private room,Brooklyn,East Flatbush
79787,NaN,NaN,Entire home/apt,Manhattan,Harlem
79788,NaN,NaN,Private room,Manhattan,Midtown
79789,NaN,NaN,Private room,Staten Island,Stapleton
87906,NaN,118.0,Private room,Brooklyn,Bedford-Stuyvesant
87907,NaN,73.0,Entire home/apt,Brooklyn,Gowanus
97710,NaN,141.0,Entire home/apt,Manhattan,Upper West Side
97711,NaN,86.0,Entire home/apt,Brooklyn,Williamsburg
97712,NaN,46.0,Private room,Brooklyn,Williamsburg
97713,NaN,112.0,Private room,Queens,Woodside
97714,NaN,124.0,Entire home/apt,Brooklyn,Fort Greene
97715,NaN,166.0,Private room,Brooklyn,Williamsburg
97716,NaN,66.0,Entire home/apt,Manhattan,West Village
97717,NaN,227.0,Private room,Brooklyn,Bedford-Stuyvesant
97718,NaN,149.0,Entire home/apt,Manhattan,Kips Bay
97719,NaN,59.0,Entire home/apt,Manhattan,East Harlem
97720,NaN,96.0,Entire home/apt,Manhattan,Kips Bay
97721,NaN,62.0,Private room,Brooklyn,Bushwick
97722,NaN,179.0,Entire home/apt,Manhattan,Midtown
97723,NaN,88.0,Private room,Staten Island,Tompkinsville
97770,NaN,185.0,Shared room,Brooklyn,Borough Park
97771,NaN,193.0,Shared room,Brooklyn,Gravesend
97772,NaN,34.0,Entire home/apt,Queens,Jamaica Estates
97773,NaN,29.0,Entire home/apt,Brooklyn,Williamsburg
97774,NaN,234.0,Entire home/apt,Manhattan,Upper East Side
97775,NaN,163.0,Entire home/apt,Manhattan,Upper East Side
97776,NaN,58.0,Private room,Manhattan,Harlem
97777,NaN,112.0,Entire home/apt,Manhattan,Gramercy
97778,NaN,69.0,Entire home/apt,Manhattan,SoHo
102045,NaN,NaN,Private room,Queens,Rego Park
102046,NaN,NaN,Private room,Brooklyn,Bushwick
102047,NaN,NaN,Private room,Brooklyn,Williamsburg
102048,NaN,NaN,Entire home/apt,Manhattan,Upper West Side
102049,NaN,NaN,Entire home/apt,Manhattan,Hell's Kitchen
102050,NaN,NaN,Entire home/apt,Brooklyn,Bedford-Stuyvesant

In [71]:
# No transformations or imputations were applied to 'price' and 'service_fee'.

**Missing Value Cleaning & Validation Methodology:**

Missing values (NaN) were systematically addressed using domain knowledge, structural consistency checks, and spatial proximity analysis (k-NN approach) rather than arbitrary deletion:

**Metadata Removal:** The license column (100% null) was removed from the dataset.

**Textual Validation & Imputation:** Missing country values were populated based on NYC location context. For rows missing neighbourhood_group, typographical errors (e.g., manhatan, brookln) were corrected before deterministically imputing borough groups via internal neighborhood lookup with 100% accuracy.

**Spatial Proximity Analysis:** Missing sub-neighborhoods were evaluated using Euclidean distance calculations over lat and long coordinates. To eliminate synthetic bias and maintain strict data integrity, 15 records lacking exact coordinate matches were retained in their original state.

**Review & Engagement Features:** Missing values in last_review and reviews_per_month were verified as active listings with zero reviews; these records were retained as NaN to preserve valid core attributes for downstream analytics.

## <span style=" color:red"> Duplicate Value Check and Handling Operations

In [72]:
df.duplicated().sum()

np.int64(532)

In [73]:
duplicates = df[df.duplicated(keep=False)].sort_values(by=list(df.columns)) # Total duplicates.

duplicates

              id                                               name  \
9098     6026161     Upper East Side 2 bedroom- close to Hospitals-
102474   6026161     Upper East Side 2 bedroom- close to Hospitals-
9099     6026714  Close to East Side Hospitals- Modern 2 Bedroom...
102475   6026714  Close to East Side Hospitals- Modern 2 Bedroom...
9100     6027266  ACADIA Spacious 2 Bedroom Apt - Close to Hospi...
102476   6027266  ACADIA Spacious 2 Bedroom Apt - Close to Hospi...
9101     6027818    *ENCHANTMENT* Upper East Side 2 bedroom- Sunny!
102477   6027818    *ENCHANTMENT* Upper East Side 2 bedroom- Sunny!
9102     6028371        *JAMES* Amazing Spacious 2 Bedroom- Bright!
102478   6028371        *JAMES* Amazing Spacious 2 Bedroom- Bright!
9103     6028923                 Large Private Upper West Side Room
102479   6028923                 Large Private Upper West Side Room
9104     6029475    *ODYSSEY* Sunny 1 Bedroom Apt- Bright & Cheery!
102480   6029475    *ODYSSEY* Sunny 1 Bedroom Apt- Bright & Cheery!
9105     6030028      *WINDSONG* Serene 1 BR in Townhouse near Park
102481   6030028      *WINDSONG* Serene 1 BR in Townhouse near Park
9106     6030580                2BR Cozy, Large & Central Apartment
102482   6030580                2BR Cozy, Large & Central Apartment
9107     6031132                Nice room in a super nice apartment
102483   6031132                Nice room in a super nice apartment
9108     6031684                Nice 1 BR Apartment at Central Park
102484   6031684                Nice 1 BR Apartment at Central Park
9109     6032237                 Spacious one bedroom with en-suite
102485   6032237                 Spacious one bedroom with en-suite
9110     6032789    Beautiful Large Private 1 Bd w/ Mediation Space
102486   6032789    Beautiful Large Private 1 Bd w/ Mediation Space
9111     6033341                                     Bed-stuy belle
102487   6033341                                     Bed-stuy belle
9112     6033894        Private bedroom w/ roofdeck NO CLEANING FEE
102488   6033894        Private bedroom w/ roofdeck NO CLEANING FEE
9113     6034446      Book Now & Save: Spend July in New York City!
102489   6034446      Book Now & Save: Spend July in New York City!
9114     6034998  Penthouse Apt w/private roofdeck, NO cleaning fee
102490   6034998  Penthouse Apt w/private roofdeck, NO cleaning fee
9115     6035551                  Large bedroom in Astoria/LIC area
102491   6035551                  Large bedroom in Astoria/LIC area
9116     6036103                        Prime Williamsburg Location
102492   6036103                        Prime Williamsburg Location
9117     6036655                Private Room, Bath & Terrace on UWS
102493   6036655                Private Room, Bath & Terrace on UWS
9118     6037207                1BR with Roof, Balcony, best 'hood!
102494   6037207                1BR with Roof, Balcony, best 'hood!
9119     6037760                  Large room, cozy, 15min Manhattan
102495   6037760                  Large room, cozy, 15min Manhattan
9120     6038312                 Cozy apt in lively Carroll Gardens
102496   6038312                 Cozy apt in lively Carroll Gardens
9121     6038864           Private Room in Very Convenient Location
102497   6038864           Private Room in Very Convenient Location
9122     6039417                      Room for rent shared bathroom
102498   6039417                      Room for rent shared bathroom
9123     6039969    *SKYTRAIN* Studio Loft Apartment - Great Space!
102499   6039969    *SKYTRAIN* Studio Loft Apartment - Great Space!
9124     6040521          *TERRA GARDEN* 1 Bedroom Garden Apartment
102500   6040521          *TERRA GARDEN* 1 Bedroom Garden Apartment
9125     6041074                     Cozy Brooklyn Room W/ Skylight
102501   6041074                     Cozy Brooklyn Room W/ Skylight
9126     6041626                           Great for a family of 4!
102502   6041626                           Great for a family of 4!
9127     6042178                Perfect for Cat, Book, Park Lovers!
102503   6042178                Perfect for Cat, Book, Park Lovers!
9128     6042730                Private Room in large 2 bedroom apt
102504   6042730                Private Room in large 2 bedroom apt
9129     6043283           A Perfect Midtown Studio (24/hr Doorman)
102505   6043283           A Perfect Midtown Studio (24/hr Doorman)
9130     6043835                   Cozy Gem in Harlem Close to ALL!
102506   6043835                   Cozy Gem in Harlem Close to ALL!
9131     6044387                       Spanish Harlem with terrace.
102507   6044387                       Spanish Harlem with terrace.
9132     6044940                   3BR Gramercy Apt in heart of NYC
102508   6044940                   3BR Gramercy Apt in heart of NYC
9133     6045492                                NO LONGER AVAILABLE
102509   6045492                                NO LONGER AVAILABLE
9134     6046044   Discount! Mins to SOHO -Cozy, Good Sized Bedroom
102510   6046044   Discount! Mins to SOHO -Cozy, Good Sized Bedroom
9135     6046597                           Tranquility On Riverside
102511   6046597                           Tranquility On Riverside
9136     6047149             A Serene NYC Skyline Room w Breakfast!
102512   6047149             A Serene NYC Skyline Room w Breakfast!
9137     6047701                 Big 1 Bedroom Brooklyn Ditmas Park
102513   6047701                 Big 1 Bedroom Brooklyn Ditmas Park
9138     6048253                 Beautiful Cute Studio, Fort Greene
102514   6048253                 Beautiful Cute Studio, Fort Greene
9139     6048806                    1 Bedroom in Prime Williamsburg
102515   6048806                    1 Bedroom in Prime Williamsburg
9140     6049358                  Huge Loft - Heart of Williamsburg
102516   6049358                  Huge Loft - Heart of Williamsburg
9141     6049910                 The Most Efficient Efficiency Ever
102517   6049910                 The Most Efficient Efficiency Ever
9142     6050463       Beautiful apartment in awesome Clinton Hill!
102518   6050463       Beautiful apartment in awesome Clinton Hill!
9143     6051015                 Manhattan at its best! Trendy area
102519   6051015                 Manhattan at its best! Trendy area
9144     6051567                   Perfect UES; steps from Park Ave
102520   6051567                   Perfect UES; steps from Park Ave
9145     6052120                 Must Love Dogs / Bushwick Brooklyn
102521   6052120                 Must Love Dogs / Bushwick Brooklyn
9146     6052672                Sunny studio in the Upper East Side
102522   6052672                Sunny studio in the Upper East Side
9147     6053224                      15 min walk to Prospect Park!
102523   6053224                      15 min walk to Prospect Park!
9148     6053776                           Near Columbia University
102524   6053776                           Near Columbia University
9149     6054329                        Studio with East River View
102525   6054329                        Studio with East River View
9150     6054881                      Charming UWS 1-bedroom w/loft
102526   6054881                      Charming UWS 1-bedroom w/loft
9151     6055433           Whole Apartment - Beautiful Sunny Studio
102527   6055433           Whole Apartment - Beautiful Sunny Studio
9152     6055986                Furnished room in Astoria apartment
102528   6055986                Furnished room in Astoria apartment
9153     6056538                        Luxury Apt 10mins Manhattan
102529   6056538                        Luxury Apt 10mins Manhattan
9154     6057090                   Cozy & Zen Manhattan Soho Studio
102530   6057090                   Cozy & Zen Manhattan Soho Studio
9155     6057643                         Warm Cozy Manhattan Studio
102531   6057643                         Warm Cozy Manhattan Studio
9156     6058195                           Chelsea Square Apartment
102532   6058195                           Chelsea Square Apartment
9157     6058747                           Four stops to Manhattan!
102533   6058747                           Four stops to Manhattan!
9158     6059299                  Upper East Side - 1 Bedroom Queen
102534   6059299                  Upper East Side - 1 Bedroom Queen
9159     6059852                  Gorgeous Garden Apt Steps To Park
102535   6059852                  Gorgeous Garden Apt Steps To Park
9160     6060404                  Relaxing bedroom in 6br apartment
102536   6060404                  Relaxing bedroom in 6br apartment
9161     6060956                W.B. Spacious Contemporary Living 3
102537   6060956                W.B. Spacious Contemporary Living 3
9162     6061509         Cozy Bedroom in Renovated Harlem Apartment
102538   6061509         Cozy Bedroom in Renovated Harlem Apartment
9163     6062061                Giant Sunny East Williamsburg LOFT!
102539   6062061                Giant Sunny East Williamsburg LOFT!
9164     6062613                 Beautiful convenient Brooklyn loft
102540   6062613                 Beautiful convenient Brooklyn loft
9165     6063166                         Private room in sunny apt.
102541   6063166                         Private room in sunny apt.
9166     6063718                 Mid Century Beauty In East Village
102542   6063718                 Mid Century Beauty In East Village
9167     6064270                                 Nice and Cozy Room
102543   6064270                                 Nice and Cozy Room
9168     6064822                 ♡Private Rm/Women's Safe Art Home♡
102544   6064822                 ♡Private Rm/Women's Safe Art Home♡
9169     6065375                         Loft rental off of Graham!
102545   6065375                         Loft rental off of Graham!
9170     6065927                                LG Bright Apartment
102546   6065927                                LG Bright Apartment
9171     6066479                 Safe,quiet,cozy,Washington Hts Apt
102547   6066479                 Safe,quiet,cozy,Washington Hts Apt
9172     6067032                       Charming One Bedroom in UES!
102548   6067032                       Charming One Bedroom in UES!
9173     6067584                  Near Central Park & Grand Central
102549   6067584                  Near Central Park & Grand Central
9174     6068136                      Best Location near Columbia U
102550   6068136                      Best Location near Columbia U
9175     6068689                          Sunny - Large Two Bedroom
102551   6068689                          Sunny - Large Two Bedroom
9176     6069241                       LIGHTFILLED ONE BEDROOM LOFT
102552   6069241                       LIGHTFILLED ONE BEDROOM LOFT
9177     6069793                   Custom Designed Cozy Garden Apt,
102553   6069793                   Custom Designed Cozy Garden Apt,
9178     6070345                             Beautiful Private Room
102554   6070345                             Beautiful Private Room
9179     6070898                      Sublet entire apt in Brooklyn
102555   6070898                      Sublet entire apt in Brooklyn
9180     6071450                   Our beautiful apt in Fort Greene
102556   6071450                   Our beautiful apt in Fort Greene
9181     6072002                Charming & Modern One Bedroom in BK
102557   6072002                Charming & Modern One Bedroom in BK
9182     6072555                 Prime West Village w/Outdoor Patio
102558   6072555                 Prime West Village w/Outdoor Patio
9183     6073107                      Beautiful Brooklyn Brownstone
102559   6073107                      Beautiful Brooklyn Brownstone
9184     6073659                   Airy Living Room | 15 min. to GC
102560   6073659                   Airy Living Room | 15 min. to GC
9185     6074212  NO FEE RENTAL *Lease Takeover Modern Apt Downtown
102561   6074212  NO FEE RENTAL *Lease Takeover Modern Apt Downtown
9186     6074764                       1 bdr in the heart of Harlem
102562   6074764                       1 bdr in the heart of Harlem
9187     6075316                    Large 1Br Apt + Balcony in LES!
102563   6075316                    Large 1Br Apt + Balcony in LES!
9188     6075868     Clean & Cozy- Private Room by Park and Subway!
102564   6075868     Clean & Cozy- Private Room by Park and Subway!
9189     6076421                   BROWNSTONE DUPLEX HUGE 1 BEDROOM
102565   6076421                   BROWNSTONE DUPLEX HUGE 1 BEDROOM
9190     6076973                   Amazing room in uptown Manhattan
102566   6076973                   Amazing room in uptown Manhattan
9191     6077525                       Comfy room close to Columbia
102567   6077525                       Comfy room close to Columbia
9192     6078078                Furnished Bedroom in 2 Bedroom apt.
102568   6078078                Furnished Bedroom in 2 Bedroom apt.
9193     6078630            Elegant 1BR, Private Bath in Brownstone
102569   6078630            Elegant 1BR, Private Bath in Brownstone
9194     6079182                        park slope duplex with yard
102570   6079182                        park slope duplex with yard
9195     6079735                                  Sunny 1BR on UES.
102571   6079735                                  Sunny 1BR on UES.
9196     6080287                Bright spacious 1BR w high ceilings
102572   6080287                Bright spacious 1BR w high ceilings
9197     6080839    2BR apt. in converted church with large terrace
102573   6080839    2BR apt. in converted church with large terrace
9198     6081391                 Couch or space in shared apartment
102574   6081391                 Couch or space in shared apartment
9199     6081944                NYC Chauncey 2 .20 min to manhattan
102575   6081944                NYC Chauncey 2 .20 min to manhattan
9200     6082496                             Quiet Bushwick Bedroom
102576   6082496                             Quiet Bushwick Bedroom
9201     6083048                Gigantic Private Brooklyn Apartment
102577   6083048                Gigantic Private Brooklyn Apartment
9202     6083601                 Sunny & Spacious near Central Park
102578   6083601                 Sunny & Spacious near Central Park
9203     6084153                    Alexander's 2BR Luxury Quarters
102579   6084153                    Alexander's 2BR Luxury Quarters
9204     6084705                Near LGA, Citifield, US Open Tennis
102580   6084705                Near LGA, Citifield, US Open Tennis
9205     6085258       Bright Bedroom in Bustling Bed Stuy Brooklyn
102581   6085258       Bright Bedroom in Bustling Bed Stuy Brooklyn
9206     6085810                Private room in the best part of BK
102582   6085810                Private room in the best part of BK
9207     6086362                             1 BR apartment sublet.
102583   6086362                             1 BR apartment sublet.
9208     6086914                 2 block walk from the beach in NYC
102584   6086914                 2 block walk from the beach in NYC
9209     6087467                Williamsburg family home -3 bedroom
102585   6087467                Williamsburg family home -3 bedroom
9210     6088019                     Patio Oasis in Upper East Side
102586   6088019                     Patio Oasis in Upper East Side
9211     6088571                  Adorable One-Bed in Williamsburg!
102587   6088571                  Adorable One-Bed in Williamsburg!
9212     6089124           Loft Space for Events, Meetings & Shoots
102588   6089124           Loft Space for Events, Meetings & Shoots
9213     6089676                Lrg room 1 block from Prospect Park
102589   6089676                Lrg room 1 block from Prospect Park
9214     6090228                Wonderful artists' loft in Brooklyn
102590   6090228                Wonderful artists' loft in Brooklyn
9215     6090781                 Columbus Ave Apt 1 block from Park
102591   6090781                 Columbus Ave Apt 1 block from Park
9216     6091333                3BR/1 Ba in TriBeCa w/ outdoor deck
102592   6091333                3BR/1 Ba in TriBeCa w/ outdoor deck
9217     6091885                Welcoming, Clean, Cheap on St Marks
102593   6091885                Welcoming, Clean, Cheap on St Marks
9218     6092437                         Spare room in Williamsburg
102594   6092437                         Spare room in Williamsburg
9219     6092990                      Best Location near Columbia U
102595   6092990                      Best Location near Columbia U
9220     6093542                     Comfy, bright room in Brooklyn
102596   6093542                     Comfy, bright room in Brooklyn
9221     6094094                   Big Studio-One Stop from Midtown
102597   6094094                   Big Studio-One Stop from Midtown
9222     6094647                               585 sf Luxury Studio
102598   6094647                               585 sf Luxury Studio
23481   13969892        Private Room in Sunny Williamsburg location
102242  13969892        Private Room in Sunny Williamsburg location
23482   13970445                      Hamptons-esque Brooklyn Condo
102243  13970445                      Hamptons-esque Brooklyn Condo
23483   13970997                     Sunny Spacious 2 bedroom condo
102244  13970997                     Sunny Spacious 2 bedroom condo
23484   13971549   Parks, Marina and New York skyline in one place.
102245  13971549   Parks, Marina and New York skyline in one place.
23485   13972102                              Central Manhattan Apt
102246  13972102                              Central Manhattan Apt
23486   13972654  Large Private 1 Bedroom Apt in Hell's Kitchen ...
102247  13972654  Large Private 1 Bedroom Apt in Hell's Kitchen ...
23487   13973206                        4 Bed 3.5 Bath in Manhattan
102248  13973206                        4 Bed 3.5 Bath in Manhattan
23488   13973758           Comfy Queen Size Bed Near Prospect Park!
102249  13973758           Comfy Queen Size Bed Near Prospect Park!
23498   13979281                spacious 2 beds in the LES w garden
102259  13979281                spacious 2 beds in the LES w garden
23499   13979834       Private bedroom with balcony in Williamsburg
102260  13979834       Private bedroom with balcony in Williamsburg
23500   13980386                     2 bedroom family luxury modern
102261  13980386                     2 bedroom family luxury modern
23501   13980938                         Perfect Williamsburg room!
102262  13980938                         Perfect Williamsburg room!
23502   13981491                 Nice apartment near Lincoln Center
102263  13981491                 Nice apartment near Lincoln Center
23503   13982043        HUGE ROOM WITH PRIVATE KITCHEN- Manhattan -
102264  13982043        HUGE ROOM WITH PRIVATE KITCHEN- Manhattan -
34935   20295937                              Sunny and Bright Room
102265  20295937                              Sunny and Bright Room
34936   20296489           Cozy Brooklyn Room with private bathroom
102266  20296489           Cozy Brooklyn Room with private bathroom
34937   20297041  Fam-Friendly Brooklyn Brownstone w. Vintage charm
102267  20297041  Fam-Friendly Brooklyn Brownstone w. Vintage charm
34938   20297593  Huge Apartment Midtown Manhattan Empire State ...
102268  20297593  Huge Apartment Midtown Manhattan Empire State ...
34939   20298146                     Beach-side basement media room
102269  20298146                     Beach-side basement media room
34940   20298698                Apartment in the Heart of Manhattan
102270  20298698                Apartment in the Heart of Manhattan
34941   20299250               Place for sleeping and exploring NYC
102271  20299250               Place for sleeping and exploring NYC
34942   20299803                                 New York Apartment

In [74]:
df.duplicated(keep=False).sum

<bound method Series.sum of 0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
30        False
31        False
32        False
33        False
34        False
35        False
36        False
37        False
38        False
39        False
40        False
41        False
42        False
43        False
44        False
45        False
56        False
57        False
58        False
59        False
60        False
61        False
62        False
63        False
64        False
65        False
66        False
67        False
68        False
69        False
70        False
71        False
72        False
73        False
74        False
75        False
76        False
77        False
78        False
79        False
80        False
81        False
82        False
83        False
84        False
85        False
86        False
87        False
88        False
89        False
90        False
91        False
92        False
93        False
94        False
95        False
106       False
107       False
108       False
109       False
110       False
111       False
112       False
113       False
114       False
115       False
116       False
117       False
118       False
119       False
120       False
121       False
122       False
123       False
124       False
125       False
126       False
127       False
128       False
129       False
130       False
131       False
132       False
133       False
134       False
135       False
136       False
137       False
147       False
148       False
149       False
150       False
151       False
152       False
153       False
154       False
155       False
156       False
157       False
158       False
159       False
160       False
161       False
162       False
163       False
164       False
165       False
166       False
168       False
169       False
170       False
171       False
172       False
173       False
174       False
175       False
177       False
178       False
179       False
180       False
181       False
182       False
183       False
184       False
185       False
194       False
195       False
196       False
197       False
198       False
199       False
200       False
201       False
202       False
203       False
204       False
205       False
206       False
207       False
208       False
209       False
210       False
211       False
212       False
213       False
214       False
215       False
216       False
217       False
218       False
219       False
220       False
221       False
222       False
223       False
224       False
225       False
226       False
227       False
228       False
229       False
230       False
231       False
232       False
233       False
234       False
235       False
236       False
237       False
238       False
239       False
240       False
241       False
242       False
243       False
244       False
245       False
246       False
247       False
248       False
249       False
250       False
251       False
252       False
253       False
254       False
255       False
256       False
257       False
258       False
259       False
260       False
261       False
262       False
264       False
265       False
266       False
267       False
268       False
269       False
270       False
271       False
272       False
273       False
274       False
275       False
276       False
277       False
278       False
279       False
293       False
294       False
295       False
296       False
297       False
298       False
300       False
301       False
302       False
303       False
304       False
305       False
306       False
307       False
308       False
309       False
310       False
311       False
312       False
313       False
314       False
315       False
316       False
317       False
318       False
319       False
320       False
321       False
322       False
323       False
324       False
325       False
326       False
338       False
339       False
340       False
341       False
342       False
343       False
344       False
345       False
346       False
347       False
348       False
349       False
351       False
360       False
361       False
362       False
363       False
364       False
365       False
366       False
367       False
368       False
369       False
370       False
371       False
372       False
373       False
374       False
375       False
376       False
377       False
378       False
379       False
380       False
381       False
382       False
383       False
384       False
385       False
386       False
387       False
388       False
389       False
390       False
391       False
392       False
393       False
394       False
395       False
396       False
397       False
399       False
400       False
401       False
402       False
403       False
404       False
405       False
406       False
407       False
408       False
409       False
410       False
411       False
412       False
413       False
414       False
415       False
416       False
417       False
418       False
419       False
420       False
422       False
423       False
430       False
431       False
432       False
433       False
434       False
435       False
436       False
437       False
438       False
439       False
440       False
442       False
443       False
444       False
445       False
446       False
447       False
448       False
449       False
450       False
451       False
452       False
453       False
454       False
455       False
456       False
457       False
458       False
459       False
460       False
461       False
462       False
463       False
464       False
465       False
466       False
467       False
468       False
469       False
470       False
479       False
480       False
481       False
482       False
483       False
484       False
485       False
486       False
487       False
488       False
489       False
490       False
491       False
492       False
493       False
494       False
495       False
496       False
497       False
498       False
499       False
500       False
501       False
502       False
503       False
504       False
505       False
506       False
507       False
508       False
509       False
510       False
511       False
512       False
513       False
514       False
515       False
516       False
517       False
518       False
519       False
520       False
521       False
522       False
523       False
524       False
526       False
527       False
528       False
529       False
530       False
531       False
532       False
533       False
534       False
535       False
536       False
537       False
538       False
539       False
540       False
541       False
542       False
543       False
544       False
545       False
546       False
547       False
548       False
549       False
555       False
556       False
557       False
558       False
559       False
560       False
561       False
562       False
563       False
564       False
565       False
566       False
567       False
568       False
569       False
570       False
571       False
572       False
573       False
574       False
575       False
576       False
577       False
578       False
579       False
580       False
581       False
582       False
583       False
584       False
585       False
586       False
587       False
588       False
589       False
590       False
591       False
592       False
593       False
594       False
595       False
596       False
597       False
598       False
599       False
600       False
601       False
602       False
603       False
604       False
605       False
606       False
607       False
608       False
609       False
610       False
611       False
612       False
613       False
614       False
615       False
616       False
617       False
618       False
619       False
620       False
621       False
622       False
623       False
624       False
625       False
626       False
627       False
628       False
629       False
630       False
631       False
632       False
633       False
634       False
635       False
636       False
637       False
638       False
639       False
640       False
641       False
642       False
643       False
644       False
645       False
646       False
647       False
648       False
649       False
650       False
651       False
652       False
653       False
654       False
655       False
656       False
657       False
658       False
659       False
660       False
661       False
662       False
663       False
664       False
665       False
666       False
667       False
668       False
669       False
670       False
671       False
672       False
673       False
674       False
675       False
676       False
677       False
678       False
679       False
680       False
681       False
682       False
683       False
684       False
685       False
686       False
687       False
688       False
689       False
690       False
691       False
692       False
693       False
694       False
695       False
696       False
697       False
698       False
699       False
700       False
701       False
702       False
703       False
704       False
705       False
706       False
707       False
708       False
709       False
710       False
711       False
712       False
713       False
714       False
715       False
716       False
717       False
718       False
719       False
720       False
721       False
722       False
723       False
724       False
725       False
726       False
727       False
728       False
729       False
730       False
731       False
732       False
733       False
734       False
735       False
736       False
737       False
738       False
739       False
740       False
741       False
742       False
743       False
744       False
745       False
746       False
747       False
748       False
749       False
750       False
751       False
752       False
753       False
754       False
755       False
756       False
757       False
758       False
759       False
760       False
761       False
762       False
763       False
764       False
765       False
766       False
767       False
768       False
769       False
770       False
771       False
772       False
773       False
774       False
775       False
776       False
777       False
778       False
779       False
780       False
781       False
782       False
783       False
784       False
785       False
786       False
787       False
788       False
789       False
790       False
791       False
792       False
793       False
794       False
795       False
796       False
797       False
798       False
799       False
800       False
801       False
802       False
803       False
804       False
805       False
806       False
807       False
808       False
809       False
810       False
811       False
812       False
813       False
814       False
815       False
816       False
817       False
818       False
819       False
820       False
821       False
822       False
823       False
824       False
825       False
826       False
827       False
828       False
829       False
830       False
831       False
832       False
833       False
834       False
835       False
836       False
837       False
838       False
839       False
840       False
841       False
842       False
843       False
844       False
845       False
846       False
847       False
848       False
849       False
850       False
851       False
852       False
853       False
854       False
855       False
856       False
857       False
858       False
859       False
860       False
861       False
862       False
863       False
864       False
865       False
866       False
867       False
868       False
869       False
870       False
871       False
872       False
873       False
874       False
875       False
876       False
877       False
878       False
879       False
880       False
881       False
882       False
883       False
884       False
885       False
886       False
887       False
888       False
889       False
890       False
891       False
892       False
893       False
894       False
895       False
896       False
897       False
898       False
899       False
900       False
901       False
902       False
903       False
904       False
905       False
906       False
907       False
908       False
909       False
910       False
911       False
912       False
913       False
914       False
915       False
916       False
917       False
918       False
919       False
920       False
921       False
922       False
923       False
924       False
925       False
926       False
927       False
928       False
929       False
930       False
931       False
932       False
933       False
934       False
935       False
936       False
937       False
938       False
939       False
940       False
941       False
942       False
943       False
944       False
945       False
946       False
947       False
948       False
949       False
950       False
951       False
952       False
953       False
954       False
955       False
956       False
957       False
958       False
959       False
960       False
961       False
962       False
963       False
964       False
965       False
966       False
967       False
968       False
969       False
970       False
971       False
972       False
973       False
974       False
975       False
976       False
977       False
978       False
979       False
980       False
981       False
982       False
983       False
984       False
985       False
986       False
987       False
988       False
989       False
990       False
991       False
992       False
993       False
994       False
995       False
996       False
997       False
998       False
999       False
1000      False
1001      False
1002      False
1003      False
1004      False
1005      False
1006      False
1007      False
1008      False
1009      False
1010      False
1011      False
1012      False
1013      False
1014      False
1015      False
1016      False
1017      False
1018      False
1019      False
1020      False
1021      False
1022      False
1023      False
1024      False
1025      False
1026      False
1027      False
1028      False
1029      False
1030      False
1031      False
1032      False
1033      False
1034      False
1035      False
1036      False
1037      False
1038      False
1039      False
1040      False
1041      False
1042      False
1043      False
1044      False
1045      False
1046      False
1047      False
1048      False
1049      False
1050      False
1051      False
1052      False
1053      False
1054      False
1055      False
1056      False
1057      False
1058      False
1059      False
1060      False
1061      False
1062      False
1063      False
1064      False
1065      False
1066      False
1067      False
1068      False
1069      False
1070      False
1071      False
1072      False
1073      False
1074      False
1075      False
1076      False
1077      False
1078      False
1079      False
1080      False
1081      False
1082      False
1083      False
1084      False
1085      False
1086      False
1087      False
1088      False
1089      False
1090      False
1091      False
1092      False
1093      False
1094      False
1095      False
1096      False
1097      False
1098      False
1099      False
1100      False
1101      False
1102      False
1103      False
1104      False
1105      False
1106      False
1107      False
1108      False
1109      False
1110      False
1111      False
1112      False
1113      False
1114      False
1115      False
1116      False
1117      False
1118      False
1119      False
1120      False
1121      False
1122      False
1123      False
1124      False
1125      False
1126      False
1127      False
1128      False
1129      False
1130      False
1131      False
1132      False
1133      False
1134      False
1135      False
1136      False
1137      False
1138      False
1139      False
1140      False
1141      False
1142      False
1143      False
1144      False
1145      False
1146      False
1147      False
1148      False
1149      False
1150      False
1151      False
1152      False
1153      False
1154      False
1155      False
1156      False
1157      False
1158      False
1159      False
1160      False
1161      False
1162      False
1163      False
1164      False
1165      False
1166      False
1167      False
1168      False
1169      False
1170      False
1171      False
1172      False
1173      False
1174      False
1175      False
1176      False
1177      False
1178      False
1179      False
1180      False
1181      False
1182      False
1183      False
1184      False
1185      False
1186      False
1187      False
1188      False
1189      False
1190      False
1191      False
1192      False
1193      False
1194      False
1195      False
1196      False
1197      False
1198      False
1199      False
1200      False
1201      False
1202      False
1203      False
1204      False
1205      False
1206      False
1207      False
1208      False
1209      False
1210      False
1211      False
1212      False
1213      False
1214      False
1215      False
1216      False
1217      False
1218      False
1219      False
1220      False
1221      False
1222      False
1223      False
1224      False
1225      False
1226      False
1227      False
1228      False
1229      False
1230      False
1231      False
1232      False
1233      False
1234      False
1235      False
1236      False
1237      False
1238      False
1239      False
1240      False
1241      False
1242      False
1243      False
1244      False
1245      False
1246      False
1247      False
1248      False
1249      False
1250      False
1251      False
1252      False
1253      False
1254      False
1255      False
1256      False
1257      False
1258      False
1259      False
1260      False
1261      False
1262      False
1263      False
1264      False
1265      False
1266      False
1267      False
1268      False
1269      False
1270      False
1271      False
1272      False
1273      False
1274      False
1275      False
1276      False
1277      False
1278      False
1279      False
1280      False
1281      False
1282      False
1283      False
1284      False
1285      False
1286      False
1287      False
1288      False
1289      False
1290      False
1291      False
1292      False
1293      False
1294      False
1295      False
1296      False
1297      False
1298      False
1299      False
1300      False
1301      False
1302      False
1303      False
1304      False
1305      False
1307      False
1308      False
1309      False
1310      False
1311      False
1312      False
1313      False
1314      False
1315      False
1316      False
1317      False
1318      False
1319      False
1320      False
1321      False
1322      False
1323      False
1324      False
1325      False
1326      False
1327      False
1328      False
1329      False
1330      False
1331      False
1332      False
1333      False
1334      False
1335      False
1336      False
1337      False
1338      False
1339      False
1340      False
1341      False
1342      False
1343      False
1344      False
1345      False

In [75]:
df = df.drop_duplicates() # Dropping duplicate records.

In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
df.shape

(101610, 25)

In [78]:
df.sample(10)

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules
13501,8457938,Futon in Brooklyn near subway,500740808,unconfirmed,Katherine,Brooklyn,Crown Heights,40.67114,-73.93561,United States,US,False,strict,Shared room,2011,NaN,177.0,1,0,NaT,NaN,4,1,198,NaN
76893,43469340,Clean + Private Bedroom in NYC's Lower East Side,60953618175,verified,Christopher,Manhattan,East Village,40.72025,-73.97901,United States,US,True,strict,Private room,2021,1161.0,232.0,10,14,2018-07-04,0.49,4,1,7,NaN
10757,6942427,Duplex Upper East side,54062126401,verified,Robin,Manhattan,Upper East Side,40.77001,-73.95691,United States,US,True,flexible,Private room,2019,882.0,176.0,2,3,2016-07-18,0.08,3,1,80,"My ideal guests would be warm, friendly, and r..."
10169,6617675,**Dominique's NYC couch bed **sleep*shower & ...,95756435608,unconfirmed,Vie,Bronx,Eastchester,40.88211,-73.83625,United States,US,False,strict,Shared room,2022,760.0,152.0,1,1,2019-04-20,0.37,4,13,350,No smoking (indoors or outside on the property...
77789,43964201,"Не дорогая комната в Нью-Йорке, в Бруклине",50599909803,verified,Ella,Brooklyn,Coney Island,40.57751,-73.98521,United States,US,False,strict,Shared room,2022,662.0,132.0,2,1,2016-12-18,0.03,5,1,0,"Please be aware, check in is NO earlier than 6..."
49388,28278328,Comfortable clean Bedstuy private room,1254085713,verified,Angela,Brooklyn,Bedford-Stuyvesant,40.69551,-73.93951,United States,US,False,moderate,Private room,2010,709.0,142.0,1,2,2019-07-08,2.00,2,1,14,NaN
30127,17640478,"8 mins to Central Park,3 mins to Subway,Guest ...",84205734212,verified,Andrea,Manhattan,Upper East Side,40.77603,-73.95573,United States,US,False,strict,Private room,2018,94.0,19.0,3,35,2019-07-07,2.22,5,1,162,NO Smoking.
94534,53212464,Charming Art Deco Apartment on Central Park,41974629930,unconfirmed,Tony,Manhattan,Upper West Side,40.78925,-73.96757,United States,US,False,moderate,Entire home/apt,2019,568.0,114.0,6,21,2019-06-30,1.83,3,1,116,NaN
51235,29298427,ENTIRE 1 Bedroom Garden Apt in Victorian Home,89331498340,verified,Menachem,Brooklyn,Flatbush,40.63159,-73.96457,United States,US,False,flexible,Private room,2014,406.0,81.0,2,9,2022-02-27,5.40,4,1,350,NaN
101748,57196756,★ NEW 2 BEDROOM APT NEXT TO CENTRAL PARK WEST★,79951939358,unconfirmed,Inna,Manhattan,Upper West Side,40.79584,-73.96242,United States,US,False,moderate,Entire home/apt,2006,400.0,80.0,30,5,2019-05-11,0.21,5,16,200,-Please no pets -Quiet hours are from 10pm - 8...

## <span style=" color:red"> General Overview and Inspection of Column Values

In [79]:
df["room_type"].value_counts(dropna=False)

# No non-sensical values were observed across the columns.

room_type
Entire home/apt    53180
Private room       46114
Shared room         2203
Hotel room           113
Name: count, dtype: int64

In [80]:
df["cancellation_policy"].value_counts(dropna=False)

# No non-sensical values were observed across the columns.

cancellation_policy
moderate    34009
strict      33783
flexible    33743
NaN            75
Name: count, dtype: int64

In [81]:
df["host_identity_verified"].value_counts(dropna=False)

# No non-sensical values were observed across the columns.

host_identity_verified
unconfirmed    50727
verified       50605
NaN              278
Name: count, dtype: int64

In [82]:
df["country"].value_counts(dropna=False)

# No non-sensical values were observed across the columns.

country
United States    101610
Name: count, dtype: int64

In [83]:
df["country_code"].value_counts(dropna=False)

# No non-sensical values were observed across the columns.

country_code
US    101610
Name: count, dtype: int64

In [84]:
df["instant_bookable"].value_counts(dropna=False)

# No non-sensical values were observed across the columns.

instant_bookable
False    50967
True     50547
<NA>        96
Name: count, dtype: Int64

In [85]:
# Check if there are any empty string values across string columns (excluding NaN);

df.select_dtypes("object").apply(
    lambda x: (x.str.strip() == "").sum()
)

name                      0
host_identity_verified    0
host_name                 0
neighbourhood_group       0
neighbourhood             0
country                   0
country_code              0
cancellation_policy       0
room_type                 0
house_rules               0
dtype: int64

In [86]:
df.dtypes

id                                         int64
name                                      object
host_id                                    int64
host_identity_verified                    object
host_name                                 object
neighbourhood_group                       object
neighbourhood                             object
lat                                      float64
long                                     float64
country                                   object
country_code                              object
instant_bookable                         boolean
cancellation_policy                       object
room_type                                 object
construction_year                          Int64
price                                    float64
service_fee                              float64
minimum_nights                             Int64
number_of_reviews                          Int64
last_review                       datetime64[ns]
reviews_per_month                        float64
review_rate_number                         Int64
calculated_host_listings_count             Int64
availability_365                           Int64
house_rules                               object
dtype: object

In [87]:
df.head(2)

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020,966.0,193.0,10,9,2021-10-19,0.21,4,6,286,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007,142.0,28.0,30,45,2022-05-21,0.38,4,2,228,Pet friendly but please confirm with me if the...

### Save Cleaned CSV File (and parquet) & Verify

In [88]:
# Save cleaned CSV file and reload for inspection;

df.to_csv("airbnb_cleaned_yeni.csv", index=False)

In [89]:
# Reload and check the saved dataset;

df1 = pd.read_csv("airbnb_cleaned_yeni.csv")

In [90]:
df1.shape

(101610, 25)

In [91]:
df1.head(2)

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,966.0,193.0,10,9.0,2021-10-19,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,142.0,28.0,30,45.0,2022-05-21,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...

In [92]:
df1.dtypes

id                                  int64
name                               object
host_id                             int64
host_identity_verified             object
host_name                          object
neighbourhood_group                object
neighbourhood                      object
lat                               float64
long                              float64
country                            object
country_code                       object
instant_bookable                   object
cancellation_policy                object
room_type                          object
construction_year                 float64
price                             float64
service_fee                       float64
minimum_nights                      int64
number_of_reviews                 float64
last_review                        object
reviews_per_month                 float64
review_rate_number                float64
calculated_host_listings_count    float64
availability_365                  float64
house_rules                        object
dtype: object

In [93]:
df1.duplicated().sum()

np.int64(0)

In [94]:
df.shape

(101610, 25)

In [95]:
df1.shape

(101610, 25)

In [96]:
# Exporting cleaned dataset to Parquet format for optimal storage and analytical performance;

df1.to_parquet('veri.parquet', index=False)

In [97]:
# Read and open parquet format;

df2 = pd.read_parquet('veri.parquet')

In [98]:
df2.head(2)

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,966.0,193.0,10,9.0,2021-10-19,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,142.0,28.0,30,45.0,2022-05-21,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...

In [99]:
df2.shape

(101610, 25)

In [100]:
# Total number of rows in the cleaned Parquet file
print("Number of rows in the Parquet file:", len(df2))

# Number of unique IDs
print("Number of unique IDs:", df2["id"].nunique())

Number of rows in the Parquet file: 101610
Number of unique IDs: 101610

# <span style=" color:red">Conclusion & Data Readiness

The data cleaning, validation, and engineering pipeline for the New York City Airbnb dataset has been finalized following a strict data-integrity-first methodology. Rather than relying on arbitrary row deletions or naive statistical imputations, every transformation was executed based on structural verification, domain logic, and spatial analysis.

**Data Type Optimization & Schema Standardization:** Explicitly re-cast key analytical features to their proper schemas (converting dates to datetime64, ratings/counts to integers, and categorical attributes to string types) to ensure strict schema enforcement upon Power BI ingestion.

**Outlier Analysis & Cell-Level Cleaning Strategy:** 

  **minimum_nights Feature:** Identified 48 rows ($0.0468\%$) containing physically impossible values ($< 1$ or $> 365$ nights). Due to its negligible volume, these 48 rows were filtered out entirely.
  **availability_365 Feature:** Identified 3,191 invalid records ($3.1240\%$), consisting of negative values (426 rows) and entries exceeding 365 days (2,765 rows). To prevent significant information loss, a cell-level cleaning approach was adopted: invalid values were converted to NaN, fully preserving the listing's remaining valid dimensions (price, location, room type).
 
**Missing Value Cleaning & Validation Methodology:** 

   **Metadata Removal:** Dropped the license column entirely as it contained 100% missing values.
 
   **Deterministic Borough Repair:** Corrected typographical errors in neighbourhood_group (e.g., manhatan, brookln) and deterministically imputed missing borough groups using internal neighborhood mapping with 100% accuracy.
 
   **Spatial Proximity Analysis (k-NN):** Evaluated missing sub-neighborhoods using Euclidean distance calculations over latitude and longitude. For 15 records lacking exact coordinate matches, values were intentionally retained as NaN to avoid introducing synthetic bias.
 
   **Review & Engagement Logic:** Verified that listings with NaN in last_review and reviews_per_month alongside number_of_reviews == 0 simply represented unreviewed listings. Listings with a valid review_rate_number but missing text reviews were preserved as legitimate evaluation workflows (e.g., star-only ratings). All such rows were retained to preserve dimensional data.
 
**Deduplication & Data Health:** Executed full primary-key and row-level deduplication, eliminating redundant records and verifying zero hidden whitespace or empty string anomalies across string columns.
 
**High-Performance BI Integration:** Exported the sanitized dataset into Parquet format alongside CSV. This preserves exact schema data types, provides high columnar compression, and ensures maximum I/O performance during Power BI reporting.The dataset is now completely sanitized, structurally sound, and fully optimized for DAX modeling, interactive dashboard design, and spatial reporting in Power BI.